model_compression_toolkit/common/data_loader.py, tests/function_tests/test_folder_image_loader.py
The FolderImageLoader chooses a list of possible integers
among all integers of indices of the images in the folder
that we load.
In FolderImageLoader we choose the indices of the images
to sample every time, from all possible indices of the images in
the folder.
The selection was between 0 to num_of_images-1, so when the folder
contains only one image, we tried to choose indices from
an empty group.
The indices now are selected from 0 to num_of_images, so the bug
is fixed.
=> Fix bug in FolderImageLoader

.github/workflows/run_tests_suite.yml
This commit changes the behavior of the unitests workflow.
Now, instead of the tests suite, the workflow runs the feature networks tests.
In addition, a coverage report is checked against a threshold (80). If the
report's final result is below the threshold, it returns an error message and exit.
=> Update unittests workflow to use coverage

test_release
This commit changes the release script to use the PyPi server for publishing
the package. Also, this commit adds a script to test the release on testpypi.
The test script generates a tag, pushes it, uploads the package to testpypi
and removes the tag (as the actual release will need this tag).
=> Update release scripts

.github/workflows/run_tests_suite.yml, .github/workflows/run_tests_suite_tf26.yml, model_compression_toolkit/keras/back2framework/model_builder.py, model_compression_toolkit/keras/graph_substitutions/substitutions/shift_negative_activation.py, model_compression_toolkit/keras/reader/common.py
Fixed imports to support Tensorflow 2.6 and 2.7.
Added a workflow to check the tests suite using TF2.6.
Changed tests suite running to run also nigthly and manually (and not just upon a PR).
For different TF versions - changed to run nightly as well.
=> Support TF 2.6 and 2.7

.github/workflows/nightly.yml
Added an env variable to the nightly workflow so
the installation before testing it, will install this version.
=> Fix nightly to use the latest uploaded mct-nightly version

model_compression_toolkit/__init__.py, model_compression_toolkit/common/mixed_precision/distance_weighting.py, model_compression_toolkit/common/mixed_precision/mixed_precision_quantization_config.py, model_compression_toolkit/common/mixed_precision/mixed_precision_search_facade.py, model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py, model_compression_toolkit/common/similarity_analyzer.py, model_compression_toolkit/keras/mixed_precision/sensitivity_evaluation.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_percision_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
Similarity analyzer changes:
- Added NMSE and NMAE.
- Changed names in similarity_analyzer to float and fxp tensors instead of a and b.
Mixed-precision changes:
- Added a new function to compute weights of the metrics based on a correlation
of each layer to the last layer of the model.
- Changed DEFAULT_MIXEDPRECISION_CONFIG to use 2, 4 and 8 bits for searching a mixed-precision configuration.
- Removed MixedPrecisionMetricsWeighting enum and factory, and used functions to
pass to the MixedPrecisionQuantizationConfig as weighting methods.
- Changed the distance matrix type to be numpy array instead of dictionary.
- Changed the average and last_layer weighting methods to receive distance matrix instead
of receiving a graph.
=> Add correlation weighting and a configurable number of images

.github/workflows/run_tests_suite.yml, .github/workflows/run_tests_suite_tf26.yml, .github/workflows/run_tests_suite_tf27.yml, tests/keras_tests/feature_networks_tests/feature_networks/mixed_percision_test.py
Added a timeout to github actions that run tests suite - 10 minutes.
Changed mixed-precision tests to use a single image when computing
metrics (instead of 100).
=> Fix long runtime of tests suite

model_compression_toolkit/keras/back2framework/model_builder.py, model_compression_toolkit/keras/gradient_ptq/graph_update.py, model_compression_toolkit/keras/quantizer/gradient_ptq/activation_quantizer_gptq_config.py, model_compression_toolkit/keras/quantizer/gradient_ptq/activation_weight_quantizer_gptq_config.py, model_compression_toolkit/keras/quantizer/gradient_ptq/weight_quantizer_gptq_config.py, model_compression_toolkit/keras/quantizer/mixed_precision/selective_weights_quantize_config.py, model_compression_toolkit/keras/reader/common.py, model_compression_toolkit/keras/reader/connectivity_handler.py, model_compression_toolkit/keras/reader/node_builder.py, tests/keras_tests/feature_networks_tests/feature_networks/multiple_output_nodes_multiple_tensors_test.py, tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_inputs_test.py, tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_outputs_test.py, tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_unused_inputs_outputs_test.py, tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_test.py, tests/keras_tests/feature_networks_tests/feature_networks/output_in_middle_test.py
Fixed an issue in case the model to quantize contains
other inner models. The inner models should get flatten
and an import issue of Functional and Sequential from
keras caused it to fail when working with TF>2.5.
=> Fix unflatten inner Keras models

tests/keras_tests/function_tests/test_lp_search_bitwidth.py, tests/keras_tests/graph_tests/test_graph_collection.py, tests/keras_tests/graph_tests/test_graph_quantization_and_export.py
In graph and function tests in keras tests, we need to set
quantization configuration to nodes before building the graph
back to a model.
This commit adds it and fixes these tests.
=> Fix graph and function tests

.github/workflows/nightly.yml
This commit removes the running of tests suite after from the
nightly workflow.
=> Remove testing after publishing nightly

tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_test.py
Change nested model test to not quantize the input model
as it's not needed for asserting the property we
check (unrolling the inner model).
=> Fix nested model test

model_compression_toolkit/keras/quantization_facade.py
This commit fixes the imports in Keras facade by importing
KerasModelValidation only after checking that tensorflow is installed.
=> Fix imports in Keras facade

docs/.buildinfo, docs/_static/bizstyle.js, docs/_static/documentation_options.js, docs/api/api_docs/classes/DefaultDict.html, docs/api/api_docs/classes/FolderImageLoader.html, docs/api/api_docs/classes/FrameworkInfo.html, docs/api/api_docs/classes/GradientPTQConfig.html, docs/api/api_docs/index.html, docs/api/api_docs/methods/keras_post_training_quantization.html, docs/api/api_docs/methods/keras_post_training_quantization_mixed_precision.html, docs/api/api_docs/methods/set_logger_path.html, docs/api/api_docs/modules/mixed_precision_quantization_config.html, docs/api/api_docs/modules/network_editor.html, docs/api/api_docs/modules/quantization_config.html, docs/genindex.html, docs/guidelines/quickstart_keras.html, docs/guidelines/visualization.html, docs/index.html, docs/search.html, docsrc/source/conf.py
This commit fixes several things in sphinx configuration file:
The copyright year to 2022 and the version (which it is now been
taken from the init of MCT).
In addition, the docs pages were regenerated after these changes.
=> Fix year and library version in sphinx configuration file

tests/keras_tests/feature_networks_tests/feature_networks/multiple_outputs_node_tests.py
Change test in multiple_outputs_node_tests.py to use a float
configuration and change compare to check for identical predictions.
This way, we test the model outputs as the test aims to.
=> Fix test compares

.github/workflows/run_tests_suite_all_latest_frameworks.yml
Change workflow that runs all tests from
time-limit of 15 minutes to 20 minutes.
=> Prolong tests suite time-limit

model_compression_toolkit/common/post_training_quantization.py
In post_training_quantization, in apply_gptq function,
the returned graph, in case we didn't use GPTQ, was the graph
without bias correction. This commit fixes this by returning the
correct graph (the one with bias correction).
=> Fix bias correction issue

model_compression_toolkit/keras/graph_substitutions/substitutions/shift_negative_activation.py, tests/keras_tests/feature_networks_tests/feature_networks/shift_neg_activation_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
fix the shape of constant y in the shift negative activation to broadcast correctly to input_shape
=> fix negative shift substitution constant shape to match input_shape

model_compression_toolkit/common/quantization/quantization_params_generation/qparams_search.py, model_compression_toolkit/common/quantization/quantization_params_generation/symmetric_selection.py, model_compression_toolkit/common/quantization/quantization_params_generation/uniform_selection.py
* Replaced minimization algorithm in parameters selection from original default algorithm (L-BFGS-B) to Nelder-Mead - much better results for the uniform quantizer (minor changes to symmetric accuracy). Changed for both weights and activations quantization (tested sporadically for activations).
* Modified uniform quantizer parameters selection, to use -tensor_max as the min value for the initial quantization range (only for weights quantization, activations quantization remain unchanged)
=> Modified uniform & symmetric quantizers

model_compression_toolkit/common/network_editors/actions.py, model_compression_toolkit/common/post_training_quantization.py, model_compression_toolkit/common/quantization/node_quantization_config.py, model_compression_toolkit/common/substitutions/shift_negative_activation.py, tests/keras_tests/feature_networks_tests/feature_networks/shift_neg_activation_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
fixes to negative shift: 
1. change quantization of bypass nodes to unsigned
2. change quantization of post-add node to non-linear number of activation bits
network editor: fix weight bits editor
=> fixes to negative shift

model_compression_toolkit/keras/quantizer/gradient_ptq/utils.py, tests/keras_tests/feature_networks_tests/feature_networks/gptq_test.py
Previous implementation caused very small gradients on kernels, because the small value decreased the gradients for auxvar:
`weight_quantized = delta * (round(weight/delta) + clip(auxvar, MAX_LSB_SHIFT))`
new implementation:
`weight_quantized = delta * (round(weight/delta) + clip(auxvar, MAX_LSB_SHIFT*delta)/delta)`
=> fix GPTQ weight quantizer

model_compression_toolkit/common/quantization/quantization_params_generation/kl_selection.py, model_compression_toolkit/common/quantization/quantization_params_generation/qparams_search.py, model_compression_toolkit/common/quantization/quantizers/quantizers_helpers.py, model_compression_toolkit/common/quantization/quantizers/uniform_quantizers.py, tests/keras_tests/feature_networks_tests/feature_networks/gptq_test.py, tests/keras_tests/function_tests/test_fix_range_to_zero.py, tests/keras_tests/function_tests/test_uniform_quantize_tensor.py
* Vectorized search per-channel for power-of-two threshold.
* Modified fix range to include zero to work vectorized per-channel as well.
=> Vectorized per-channel for power-of-two threshold

docs/api/api_docs/classes/GradientPTQConfig.html, model_compression_toolkit/common/gptq/gptq_config.py, model_compression_toolkit/keras/gradient_ptq/gptq_loss.py, model_compression_toolkit/keras/gradient_ptq/graph_info.py, model_compression_toolkit/keras/gradient_ptq/training_wrapper.py, model_compression_toolkit/keras/quantization_facade.py
Add float and quantized kernels to GPTQ loss function API.
Changed get_trainble_parameters to return the trainable parameters as a list of lists, each containing a layer's weights for trainin, and 2 mote lists containing the quantized and float kernels of the layers to be passed to the GPTQ loss function.
=> support adding model's weights to GPTQ loss

model_compression_toolkit/hardware_models/keras_hardware_model/keras_default.py
Remove BatchNormalization from NoQuantization op set
label, as its activations are quantized.
=> Remove BatchNormalization from Keras default model

model_compression_toolkit/common/hardware_representation/op_quantization_config.py, model_compression_toolkit/hardware_models/default_hwm.py, model_compression_toolkit/hardware_models/keras_hardware_model/keras_default.py, model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_default.py, model_compression_toolkit/hardware_models/qnnpack.py, model_compression_toolkit/hardware_models/tflite.py, tests/common_tests/test_hardware_model.py, tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py, tests/keras_tests/feature_networks_tests/feature_networks/symmetric_threshold_selection_activation_test.py, tests/keras_tests/feature_networks_tests/feature_networks/test_kmeans_quantizer.py, tests/keras_tests/feature_networks_tests/feature_networks/uniform_range_selection_activation_test.py, tests/keras_tests/function_tests/test_kl_error_quantization_configurations.py, tests/keras_tests/function_tests/test_quantization_configurations.py, tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py, tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
Refactor default hardware model to allow generating new models for tests and experiments, while keeping the framework hardware modeling mapping
=> refactor default hw model

model_compression_toolkit/common/bias_correction/compute_bias_correction_of_graph.py, tests/keras_tests/feature_networks_tests/feature_networks/bias_correction_dw_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
Add support for bias correction in Keras DepthwiseConv2d
when depth_multiplier is greater than 1.
=> Fix bias correction for Keras Depthwise

model_compression_toolkit/common/mixed_precision/sensitivity_evaluation_manager.py, model_compression_toolkit/keras/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/pytorch/mixed_precision/sensitivity_evaluation.py, tests/keras_tests/function_tests/test_lp_search_bitwidth.py
Reduce the number of interest points for mp metric evaluation from the entire set of configurable nodes to only the outputs of convolutional layers.
=> Change mixed-precision sensitivity metric interest points

tests/keras_tests/test_keras_hardware_model.py, tests/pytorch_tests/test_pytorch_hardware_model.py
Removed get_model tests from Keras and Pytorch
as they take too much time due to long Symmetric and Uniform
thresholds search.
=> Remove get_model tests

model_compression_toolkit/common/post_training_quantization.py
To allow applying the operations required in order to create a finalized graph as an external API, without going through the entire post_training_quantization operation.
=> Extract graph substitutions and editing to external function

.github/workflows/run_tests_suite_tf25.yml, .github/workflows/run_tests_suite_tf26.yml, .github/workflows/run_tests_suite_tf27.yml
In nightly tests for different Tensorflow versions
(2.5, 2.6, 2.7) there is a timeout. This is not needed
thus it's removed.
=> Remove timeout in nightly TF testssuite

model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py, tests/keras_tests/tpc_keras.py
Added TFOpLambda type layers to the list of NoQuantization in the default keras  tpc
=> added layers types for keras default tpc NoQuantization list

model_compression_toolkit/common/quantization/set_node_quantization_config.py, model_compression_toolkit/keras/back2framework/model_builder.py
* TFOpLambda layers are not supported in activation mixed precision
* Use QuantizeWrapper in model builder only on configurable nodes
=> fix issue in model builder for mixed precision

model_compression_toolkit/__init__.py, model_compression_toolkit/common/framework_implementation.py, model_compression_toolkit/common/mixed_precision/bit_width_setter.py, model_compression_toolkit/common/mixed_precision/kpi.py, model_compression_toolkit/common/mixed_precision/kpi_data.py, model_compression_toolkit/common/mixed_precision/mixed_precision_quantization_config.py, model_compression_toolkit/common/mixed_precision/mixed_precision_search_facade.py, model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py, model_compression_toolkit/common/network_editors/edit_network.py, model_compression_toolkit/common/post_training_quantization.py, model_compression_toolkit/common/quantization/core_config.py, model_compression_toolkit/common/quantization/debug_config.py, model_compression_toolkit/common/quantization/quantization_config.py, model_compression_toolkit/common/quantization/set_node_quantization_config.py, model_compression_toolkit/common/substitutions/shift_negative_activation.py, model_compression_toolkit/common/target_platform/op_quantization_config.py, model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py, model_compression_toolkit/keras/graph_substitutions/substitutions/shift_negative_activation.py, model_compression_toolkit/keras/keras_implementation.py, model_compression_toolkit/keras/kpi_data_facade.py, model_compression_toolkit/keras/quantization_facade.py, model_compression_toolkit/pytorch/graph_substitutions/substitutions/shift_negative_activation.py, model_compression_toolkit/pytorch/kpi_data_facade.py, model_compression_toolkit/pytorch/pytorch_implementation.py, model_compression_toolkit/pytorch/quantization_facade.py, model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py, tests/keras_tests/function_tests/test_lp_search_bitwidth.py, tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py, tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
**Add a new API, currently dubbed "experimental":**
separate QuantizationConfig & MixedPrecisionConfig and put both under CoreConfig.
put analyze_similarity and network_editor in DebugConfig, under CoreConfig too.
**new APIs:**
keras_post_training_quantization_experimental
keras_gradient_post_training_quantization_experimental
pytorch_post_training_quantization_experimental
pytorch_gradient_post_training_quantization_experimental
Old APIs are still supported and will be deprecated in future releases
=> Api change

model_compression_toolkit/pytorch/graph_substitutions/substitutions/linear_collapsing.py, tests/pytorch_tests/model_tests/feature_models/linear_collapsing_test.py
This PR fixes two issues:
1. Missing conversion to torch tensor during the substitution.
2. A PyTorch test used a Keras generating TPC function.
=> Fix linear collapsing issues

requirements.txt
An issue occurs when using networkx 2.8.1 during deepcopy
of the graph. This downgrade solve the issue.
=> Update requirements file to use networkx 2.8.0

tests/keras_tests/function_tests/test_sensitivity_metric_interest_points.py, tests/test_suite.py
MP filterring interest-points tests did not pass the "mp enable"
flag during candidates creation to nodes.
The tests class was renamed as well due to a typo.
=> Fix issue with MP interest-point filtering test

docsrc/source/index.rst
Add Technical Constrains to docs: output structure may not be preserved after optimization (related to issue #114 )
=> Add Technical Constrains to docs

model_compression_toolkit/common/post_training_quantization.py, model_compression_toolkit/keras/quantization_facade.py, model_compression_toolkit/pytorch/quantization_facade.py
remove duplicate arguments from common.post_training_quantization:
analyze_similarity, network_editor & n_iter (all moved to CoreConfig)
=> remove duplicate arguments from post_training_quantization

model_compression_toolkit/common/fusion/layer_fusing.py, model_compression_toolkit/common/target_platform/targetplatform2framework/operations_to_layers.py, model_compression_toolkit/tpc_models/default_tp_model.py, model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py, model_compression_toolkit/tpc_models/pytorch_tp_models/pytorch_default.py, tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_inputs_test.py
1. Adding some fusions to TPC, relevant to mobilenetv3, pytorch
2. There is a bug that we declare fusion when only some layers from fusion are found and not the whole pattern.
This fix checks the candidate fusion to see if the entire fusion is found.
=> Add new fusions to default TPC and fix issue in fusion algorithm

model_compression_toolkit/common/quantization/node_quantization_config.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/edit_error_method_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
During editing a node's quantization error method, there is an issue that the function
to compute the quantization params is not edited as well.
This commit fixes this issue by changing activation_error_method to a property so this
is taken care of in its setter.
=> Fix issue: Editing error method has no effect

model_compression_toolkit/common/mixed_precision/bit_width_setter.py, model_compression_toolkit/common/network_editors/edit_network.py, model_compression_toolkit/common/post_training_quantization.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/change_qc_attr_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py, tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
Some actions regard the final quantization configuration do not
affect the network as the editing is done at the beggining of the
optimization process. This commits fix this by editing the network
one more time after finalizing the quantization configurations.
=> Fix issue: network editor doesnt affect final configs

model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation_manager.py, model_compression_toolkit/core/common/similarity_analyzer.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py
Fixed minor bugs in MP metric calculation  - added epsilon to division in KL distance function, changed default to MSE (instead of NMSE) and removed unnecessary argument from call to distance computation
=> Fixed minor bugs in MP metric calculation 

model_compression_toolkit/core/keras/constants.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
Replace layers.Dot & layers.Dense with tf.matmul & layers.Conv2D (1x1) in MHA decomposition substitution
Removes the need to reuse Dense nodes when MHA iteration is required
=> Mha sub update

model_compression_toolkit/core/pytorch/reader/reader.py, tests/pytorch_tests/model_tests/feature_models/add_net_assert_test.py, tests/pytorch_tests/model_tests/feature_models/remove_assert_test.py, tests/pytorch_tests/model_tests/feature_models/remove_broken_node_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Remove from Pytorch graph reader nodes without output (like assert)
=> Pytorch remove asserts from graph

model_compression_toolkit/core/pytorch/reader/graph_builders.py, model_compression_toolkit/core/tpc_models/default_tpc/v3/tpc_pytorch.py
1. Fix getattr operation in pytorch graph builder
2. Add unbind (pytorch) to non-quantization TPC list
=> Fix pytorch builder for getattr and add unbind to non-quant list

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/model_builder_mode.py, model_compression_toolkit/core/keras/back2framework/model_builder.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/keras/quantization_facade.py, model_compression_toolkit/core/pytorch/back2framework/model_builder.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, model_compression_toolkit/gptq/common/gptq_training.py, model_compression_toolkit/gptq/keras/gptq_training.py, model_compression_toolkit/gptq/keras/model_builder.py
Separate GPTQ code in model builder to s separate model builder in GPTQ. the GPTQ model builder first calls the core model builder, and then adds the GPTQ QuantizationWrappers
=> Separate GPTQ from model builder

model_compression_toolkit/core/tpc_models/default_tpc/v2/tp_model.py, model_compression_toolkit/core/tpc_models/default_tpc/v2/tpc_pytorch.py, model_compression_toolkit/core/tpc_models/default_tpc/v3/tp_model.py, model_compression_toolkit/core/tpc_models/default_tpc/v3/tpc_pytorch.py, model_compression_toolkit/core/tpc_models/tflite_tpc/v1/tp_model.py, model_compression_toolkit/core/tpc_models/tflite_tpc/v1/tpc_keras.py
Fix irrelevant TPC related logs by combining OperatorSets which are relevant only for specific framework (therefore, caused the warning about not being defined in a the other framework's TPC).
Merged: Haedswish into Swish OpratorSet and DepthwiseConv2D into Conv2d OperatorSet.
=> Fix irrelevant TPC logs

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/keras/back2framework/model_gradients.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/back2framework/model_gradients.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/keras_tests/function_tests/test_model_gradients.py, tests/pytorch_tests/function_tests/model_gradients_test.py, tests/pytorch_tests/function_tests/test_function_runner.py
* Added support to gradient-based weights for the distance metric computation in Pytorch framework.
* Default value for alpha parameter (tuning between output layers and regular layers) is changed to 0.3 (based on experimental study).
* Default weights for metric computation remained uniform (gradient-based weights option needs to be activated by an argument to mixed-precision quantization config).
* Minor fix in Keras gradient model tests TPC imports.
=> PyTorch support for gradient-based weights for mixed-precision metric

model_compression_toolkit/core/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
use Reshape instead of Stack to collect iterations output in case there are no iterations ([Batch, N, C] * iters ==> [Batch, iters, N, C])
=> MHA substitution: use Reshape instead of Stack to collect iterations

model_compression_toolkit/core/tpc_models/default_tpc/target_platform_capabilities.py, model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/__init__.py, model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/tp_model.py, model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/tpc_keras.py, model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/tpc_pytorch.py
Added Mixed-Precision LUT TPC. 
Enables execution of mixed-precision quantization using non-uniform quantizer for 2 and 4 bits.
=>  Mixed-Precision LUT TPC

tutorials/example_keras_mobilenet_mixed_precision.py, tutorials/example_keras_mobilenet_mixed_precision_lut.py, tutorials/example_pytorch_mobilenet_mixed_precision_lut.py
Added tutorials for weights mixed-precision quantization with LUT quantizer for 2 and 4 bits candidates (for both Keras and Pytorch).
Also, changed Keras MP tutorial to work with MobileNetV2 and updated comments.
=> Mixed-Precision LUT tutorials

docsrc/source/api/experimental_api_docs/index.rst, docsrc/source/api/experimental_api_docs/methods/keras_quantization_aware_training_export.rst, docsrc/source/api/experimental_api_docs/methods/keras_quantization_aware_training_init.rst, docsrc/source/index.rst, model_compression_toolkit/__init__.py, model_compression_toolkit/core/common/defaultdict.py, model_compression_toolkit/core/common/framework_info.py, model_compression_toolkit/qat/keras/model_builder.py, model_compression_toolkit/qat/keras/quantization_facade.py, tests/keras_tests/feature_networks_tests/feature_networks/qat_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
1. Add weight quantization in case there are weights not to be fine-tuned
2. Add export method to remove QuantizeWrappers from the QAT model after fine-tuning
3. Update docsrc with new API
=> update QAT and add export API

tests/keras_tests/function_tests/test_model_gradients.py
Minor fix to Keras model gradients test for an error caused by previous update which changed the model gradients method functionality.
=> Minor fix to Keras model gradients test

model_compression_toolkit/qat/keras/quantizer/ste_rounding/symmetric_ste.py, tests/keras_tests/feature_networks_tests/feature_networks/qat_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tutorials/example_pytorch_quantization_mnist.ipynb
Fix bug with weight quantization per output channel when channel axis isn't the last axis
=> Support DW-Conv2D in QAT when quantizing per weights per channel

model_compression_toolkit/core/keras/constants.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/shift_negative_activation.py, tests/keras_tests/feature_networks_tests/feature_networks/shift_neg_activation_test.py
In shift negative substitution, use TFOpLambda to create Add
and Pad layers instead of TensorFlowOpLayer.
=> Replace TensorFlowOpLayer with TFOpLambda in SNC

model_compression_toolkit/core/common/constants.py, model_compression_toolkit/core/common/graph/base_graph.py, model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/common/graph/virtual_activation_weights_node.py, model_compression_toolkit/core/common/quantization/candidate_node_quantization_config.py, model_compression_toolkit/core/common/quantization/filter_nodes_candidates.py, model_compression_toolkit/core/common/quantization/set_node_quantization_config.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/virtual_activation_weights_composition.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/weight_activation_split.py, tests/keras_tests/function_tests/test_activation_weights_composition_substitution.py, tests/keras_tests/function_tests/test_weights_activation_split_substitution.py
This is a PR that include new substitutions and classes as part of several PRs that will eventually incorporate Bit-Operations KPI into our Mixed-precision search.
This PR includes the following additions:
- Implemented WeightsActivationSplit and VirtualActivationWeightsComposition substitutions, to prepare a virtual computation graph for mixed-precision search with bit-operations KPI constraint.
- Implemented virtual nodes classes for constructing the virtual graph.
- Several peripheral modifications.
=> Graph substitutions for weight and activation composition (BOPs KPI preparations)

model_compression_toolkit/gptq/common/gptq_config.py, model_compression_toolkit/gptq/common/gptq_training.py, model_compression_toolkit/gptq/keras/gptq_training.py, model_compression_toolkit/gptq/keras/quantization_facade.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/keras_tests/tpc_keras.py
This PR fixes several issues in GPTQ experimental facade:
1. Copying graphs in GPTQ trainers.
2. Skip micro training loop if there are no parameters to train.
3. Return the correct graph in the experimental facade.
4. Fix documentation in examples of the facade.
=> Fix gptq experimental facade

tests/keras_tests/test_fully_quantized_exporter.py
In sanity check for new exporter we choose an integer randomly.
It creates a list of a single integer, and this commit fix it to take
an integer.
=> Fix fully quantized sanity test

model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py
Skip computation of KPI when calculating KPI matrix for min configuration (for all KPI targets).
Since we compute the difference from the minimal KPI (for the minimal bit-width) the result for min config would be 0 every time for all entries in the results vector, thus, we can skip it to save runtime.
=> Skip computation of KPI when calculating KPI matrix for min configuration

model_compression_toolkit/core/common/constants.py, model_compression_toolkit/core/common/graph/virtual_activation_weights_node.py, model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_data.py, model_compression_toolkit/core/common/substitutions/virtual_activation_weights_composition.py, model_compression_toolkit/core/common/substitutions/weights_activation_split.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/weights_activation_split.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/virtual_activation_weights_composition.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/weights_activation_split.py, model_compression_toolkit/core/pytorch/kpi_data_facade.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/keras_tests/function_tests/test_activation_weights_composition_substitution.py, tests/keras_tests/function_tests/test_weights_activation_split_substitution.py, tests/pytorch_tests/model_tests/base_pytorch_test.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_bops_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Support BOPs KPI in Pytorch.
Virtual graph substitutions were moved to a common location and created framework specific substitutions wrappers for both Pytorch and Keras.
Also required small modification to VirtualSplitActivationNode.
=> Bit-operations count implementation in Pytorch

model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py, model_compression_toolkit/gptq/runner.py, tutorials/example_keras_mobilenet_gptq.py, tutorials/example_keras_mobilenet_gptq_mixed_precision.py
GPTQ log was removed as it is unneeded.
Skip GPTQ training if number of iterations is 0.
Add tutorial to run GPTQ facade.
=> GPTQ fixes: remove unneeded log, skip gptq training when n_iter=0

model_compression_toolkit/core/common/mixed_precision/mixed_precision_quantization_config.py, model_compression_toolkit/core/keras/back2framework/model_gradients.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py, tests/keras_tests/function_tests/test_lp_search_bitwidth.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_bops_test.py
Fixed problematic tests in tests suit:
- Remove gradients computation in LP search test
- Reduced input and convolutions sizes in mixed-precision feature tests
- Minor fix in gradients computation (casting the outputs of layer with multiple outputs to float32 for gradients tracking)
=> Fix tests suit runtime

model_compression_toolkit/core/keras/back2framework/instance_builder.py, model_compression_toolkit/core/keras/back2framework/keras_model_builder.py, model_compression_toolkit/gptq/keras/gptq_model_builder.py
Add mapping in Keras model builder from layers to their graph nodes. This is since there are times we rely on the layer's name (during cloning in GPTQ, MP, etc.) but the layer's in the final model can be different from the node's name, so we save a mapping of the layer's output tensor to the node.
=> Change GPTQ node search method

model_compression_toolkit/core/keras/back2framework/mixed_precision_model_builder.py, model_compression_toolkit/qat/keras/qat_model_builder.py
Use mapping in KerasModelBuilder from layers to nodes during MP and QAT model cloning.
=> Change MP and QAT node search method

tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
Change test to check properties of the test instead of checking cosine similarity.
=> Fix MP keras DW test

model_compression_toolkit/core/common/constants.py, model_compression_toolkit/gptq/common/gptq_config.py, model_compression_toolkit/gptq/keras/gptq_loss.py, model_compression_toolkit/gptq/keras/quantization_facade.py, model_compression_toolkit/gptq/keras/quantizer/configs/weight_quantizer_gptq_config.py, model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/gumbel_softmax.py, model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/symmetric_gumbel.py
- Minor changes in default parameters to Keras GPTQ facade.
- Added a 'gumbel_scale' argument to gumbel softmax.
=> Updating MCT default GPTQ arguments with Gumbel Rounding compatible values

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/graph/base_graph.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_facade.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py
Disable activation quantization in mixed-precision metric computation when running mixed precision with target weights KPI only or for nodes that have only single activation candidates (so they are not part of the MP search)
=> Disable activation quantization in mixed-precision metric computation for only weight MP search

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, model_compression_toolkit/gptq/common/gptq_training.py
In case of an incompatible output node for jacobian-based weights computation (argmax or softmax), the output nodes of the model will be replaced for the sake of the computation of the weight only.
This solution is similar to the one implemented for mixed-precision weights but it does not alter the interest points list like in mixed-precision.
=> Replace output node for jacobian-based weights computation for GPTQ 

tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
MP test for Depthwise layer checks CS for no reason. This commit removes the check.
=> Remove checking CS in MP test

tests/keras_tests/feature_networks_tests/feature_networks/input_scaling_test.py
The test have an issue when one of the weights of the first linear layer has a weight of 0, which caused the division to be inf. This commit fixes this issue.
=> Fix input scale test

model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_data.py, model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_methods.py, tests/common_tests/function_tests/test_kpi_object.py
- kpi_data - removed unnecessary condition from total bops
- kpi_methods - removed unnecessary condition from BOPs KPI method - no need to check if mp_cfg is not empty because there is no separate behavior for this case
- kpi - added dedicated tests for KPI object
=> Mixed precision tests coverage - KPI

model_compression_toolkit/exporter/fully_quantized/keras/builder/fully_quantized_model_builder.py, model_compression_toolkit/exporter/fully_quantized/keras/extended_quantize_wrapper.py
Change to stop trying to get output_shape for reused layers (as it does not exist).
To use ExtendedQuantizeWrapper for reused layers, we pass None as this is meaningless for reused layers
(they do not have compute_output_shape anyway).
=> Fix fully quantized model builder for reused layers

model_compression_toolkit/core/common/substitutions/shift_negative_activation.py
Add Z threshold to shift negative activation substitution parameter search option
=> Shift Negative substitution params search fix

model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py, tests/keras_tests/function_tests/test_export_keras_fully_quantized_model.py
Change the unwrapping of a layer with NoOpQuantizeConfig to keep using ExtendedQuantizeWrapper since there's an issue for TensorFlow to clone_model such a model due to mismatch shapes (it adds a new axis at index 0 with the value of 1).
=> Fix TF fake quant exporter

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/back2framework/mixed_precision_model_builder.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
* Added framework-dependent inference method for mixed precision sensitivity evaluation.
* Added a test for Pytorch mixed precision with multiple inputs and concat layer.
* Small syntax refactor in Pytorch mixed precision tests.
=> Fix Pytorch mixed precision with multiple inputs

model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_methods.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
Total method considered reused nodes as configurable nodes, when it should not. This commit fixes this.
=> Fix MP total KPI method

model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py, model_compression_toolkit/exporter/model_exporter/tflite/__init__.py, model_compression_toolkit/exporter/model_exporter/tflite/fakely_quant_tflite_exporter.py, model_compression_toolkit/exporter/model_exporter/tflite/tflite_export_facade.py, model_compression_toolkit/exporter/model_wrapper/keras/validate_layer.py, tests/keras_tests/function_tests/test_export_keras_fully_quantized_model.py
Add TFLite exporter for fake-quant models.
The exporter uses the TF exporter first to convert the weights to FQ, and then convert it to TFLite using TFLite converter.
=> Add TFLite fake quant exporter

model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/back2framework/model_gradients.py, model_compression_toolkit/core/pytorch/back2framework/model_gradients.py, model_compression_toolkit/gptq/common/gptq_config.py, model_compression_toolkit/gptq/common/gptq_training.py, model_compression_toolkit/gptq/keras/gptq_training.py, model_compression_toolkit/gptq/keras/quantizer/configs/weight_quantizer_gptq_config.py, model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py, model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/symmetric_gumbel.py, model_compression_toolkit/gptq/pytorch/gptq_training.py, model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/base_gumbel_weights_quantizer.py, model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/sym_gumbel_weights_quantizer.py, model_compression_toolkit/qunatizers_infrastructure/keras/quantize_wrapper.py
The following additions to Gumbel Rounding, GPTQ, and Jacobian weights computation:
* Normalization to weights using log scale.
* Added option for different gumbel scale values per bit-width.
* Moved gumbel_scale parameter to GumbelConfig instead of GradientPTQConvifg.
* Added tqdm to model_gradients random interest points and GPTQ training loops.
=> Additions to Gumbel Rounding

model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py
ONNX opset version 16 is not supported in torch 1.11. This commit adds a fix that sets the correct opset version according to the torch version.
=> Fix issue in onnx exporter

model_compression_toolkit/__init__.py, model_compression_toolkit/exporter/README.md, model_compression_toolkit/exporter/model_exporter/__init__.py, model_compression_toolkit/exporter/model_exporter/keras/keras_export_facade.py, model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py, model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_torchscript_pytorch_exporter.py, model_compression_toolkit/exporter/model_exporter/pytorch/pytorch_export_facade.py, model_compression_toolkit/exporter/model_exporter/tflite/tflite_export_facade.py, model_compression_toolkit/exporter/model_wrapper/__init__.py, model_compression_toolkit/exporter/model_wrapper/pytorch/validate_layer.py, tests/keras_tests/exporter_tests/tflite_int8/tflite_int8_exporter_base_test.py, tests/pytorch_tests/function_tests/test_export_pytorch_fully_quantized_model.py
Add exporter README (only keras examples for now)
Fix facades APIs in all frameworks:
- file path is mandatory
- validation function is optional
Add validation function to pytorch exporter.
=> Fixes in exporter

model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py
Limit ILP solver to 60 seconds. Use PULP_CBC_CMD as the default solver (as this is PuLP's default solver).
=> Limit ILP runtime

model_compression_toolkit/core/pytorch/constants.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/reshape_with_static_shapes.py, tests/pytorch_tests/model_tests/feature_models/dynamic_size_inputs_test.py
After the fix the batch size would infer from the length of the array and remaining dimensions of the input to the reshape and view operators.
=> Change PyTorch reshape and view operators batch size value

model_compression_toolkit/gptq/common/gptq_config.py, model_compression_toolkit/gptq/common/gptq_constants.py, model_compression_toolkit/gptq/common/gptq_training.py, model_compression_toolkit/gptq/keras/quantization_facade.py, model_compression_toolkit/gptq/keras/quantizer/quantization_builder.py, model_compression_toolkit/gptq/keras/quantizer/regularization_factory.py, model_compression_toolkit/gptq/keras/quantizer/soft_rounding/soft_quantizer_reg.py, model_compression_toolkit/gptq/keras/quantizer/soft_rounding/symmetric_soft_quantizer.py, model_compression_toolkit/gptq/keras/quantizer/ste_rounding/symmetric_ste.py, model_compression_toolkit/gptq/pytorch/quantization_facade.py, model_compression_toolkit/gptq/pytorch/quantizer/quantization_builder.py, model_compression_toolkit/gptq/pytorch/quantizer/regularization_factory.py, model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/soft_quantizer_reg.py, model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/symmetric_soft_quantizer.py, tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py, tests/keras_tests/function_tests/test_get_gptq_config.py, tests/keras_tests/models_tests/test_networks_runner.py, tests/pytorch_tests/function_tests/get_gptq_config_test.py, tests/pytorch_tests/model_tests/feature_models/gptq_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Two main modifications:
* Removed quantization_parameters_learning and lsb_change_per_bit_width arguments from GPTQ config and replaced them with gptq_quantizer_params_override dictionary.
* Changed GPTQ soft quantizer regularization from function to class and fixed linear decay initialization.
=> Override parameters for GPTQ config and fix regularization

model_compression_toolkit/gptq/common/gptq_config.py, model_compression_toolkit/gptq/keras/quantizer/soft_rounding/symmetric_soft_quantizer.py, model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/symmetric_soft_quantizer.py, tests/keras_tests/function_tests/test_gptq_soft_quantizer.py, tests/pytorch_tests/function_tests/test_gptq_soft_quantizer.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py, tests/test_suite.py
Fixing two issues:
* In both Pytorch and Keras Soft quantizers - parameters learning wasn't applied for per-tensor quantization.
* In Keras Soft quantizer - per-tensor quantization did not use the soft targets.
=> Fix bug with parameters learning in GPTQ soft quantizers

model_compression_toolkit/core/common/quantization/node_quantization_config.py, tests/keras_tests/feature_networks_tests/feature_networks/per_tensor_weight_quantization_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
When creating quantization configuration for weights the per-tensor/per-channel information was taken from the global quantization configuration instead of TPC. This commit fixes this.
=> Fix cfg creation in weights quantization granularity

model_compression_toolkit/gptq/keras/quantization_facade.py, tutorials/example_keras_mobilenet_gptq_mixed_precision.py, tutorials/example_keras_mobilenet_mixed_precision.py, tutorials/example_keras_mobilenet_mixed_precision_lut.py
Add arguments to Keras tutorials.
Add use_hessian_based_weights to get_keras_gptq_config API (True by default).
=> Add arguments for Keras tutorials

model_compression_toolkit/__init__.py, model_compression_toolkit/core/common/constants.py, model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, model_compression_toolkit/gptq/common/gptq_framework_implementation.py, model_compression_toolkit/gptq/keras/gptq_keras_implementation.py, model_compression_toolkit/gptq/keras/quantization_facade.py, model_compression_toolkit/gptq/keras/quantizer/soft_rounding/uniform_soft_quantizer.py, model_compression_toolkit/gptq/pytorch/gptq_pytorch_implementation.py, model_compression_toolkit/gptq/pytorch/quantization_facade.py, model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/uniform_soft_quantizer.py, model_compression_toolkit/qat/__init__.py, model_compression_toolkit/qat/common/__init__.py, model_compression_toolkit/qat/keras/quantizer/ste_rounding/symmetric_ste.py, model_compression_toolkit/qat/keras/quantizer/ste_rounding/uniform_ste.py, model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/symmetric_ste.py, model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/uniform_ste.py, model_compression_toolkit/quantizers_infrastructure/constants.py, model_compression_toolkit/quantizers_infrastructure/trainable_infrastructure/common/get_quantizers.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/pytorch_tests/model_tests/feature_models/qat_test.py, tests/quantizers_infrastructure_tests/trainable_infrastructure_tests/keras/test_keras_trainable_infra_runner.py, tests/quantizers_infrastructure_tests/trainable_infrastructure_tests/pytorch/test_pytorch_trainable_infra_runner.py
This commit includes imports reordering which includes:
1. Moving QAT related API from main mct to mct.qat
2. Moving constants that are used by gptq and qat to the core constants (instead of being in qat constants).
3. Moving get_gptq_trainer_obj from FrameworkImplementation to a new class called GPTQFrameworkImplementation.
4. Adding 2 new classes (per-framewrok) that inherits GPTQFrameworkImplementation.
=> Rearrange QAT imports

model_compression_toolkit/qat/keras/quantization_facade.py, model_compression_toolkit/qat/keras/quantizer/quantization_builder.py, model_compression_toolkit/quantizers_infrastructure/inferable_infrastructure/keras/activation_quantization_holder.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
Use ActivationQuantizationHolder for QAT ready models. The wrappers that were used for QAT are no longer hold the activation quantizers.
=> Qi refactor qat

model_compression_toolkit/quantizers_infrastructure/inferable_infrastructure/keras/quantizers/activation_inferable_quantizers/activation_lut_pot_inferable_quantizer.py, model_compression_toolkit/quantizers_infrastructure/inferable_infrastructure/keras/quantizers/activation_inferable_quantizers/activation_uniform_inferable_quantizer.py, model_compression_toolkit/quantizers_infrastructure/inferable_infrastructure/keras/quantizers/weights_inferable_quantizers/weights_lut_pot_inferable_quantizer.py, model_compression_toolkit/quantizers_infrastructure/inferable_infrastructure/keras/quantizers/weights_inferable_quantizers/weights_lut_symmetric_inferable_quantizer.py, tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py, tests/keras_tests/feature_networks_tests/feature_networks/uniform_range_selection_activation_test.py, tests/quantizers_infrastructure_tests/inferable_infrastructure_tests/keras/inferable_keras/test_activation_inferable_quantizers.py, tests/quantizers_infrastructure_tests/inferable_infrastructure_tests/keras/inferable_keras/test_load_model.py, tests/quantizers_infrastructure_tests/inferable_infrastructure_tests/keras/inferable_keras/test_weights_lut_inferable_quantizer.py, tests/quantizers_infrastructure_tests/inferable_infrastructure_tests/keras/test_keras_inferable_infra_runner.py
Fix issues with inferable quantizers:
1. Keras quantizers should receive list in their init instead of np arrays. The reason for that is that during deserialization keras build the quantizers with lists (even if they were saved as np arrays).
2. In LUT weight quantizers the kernel had dtype of float64 which failed inference. The reason for this is that by default numpy arrays are float64. This commit fixes this by explicity stating the dtype to be float32.
=> Fix inferable quantizers serialization and inference issues

model_compression_toolkit/__init__.py, tests/keras_tests/feature_networks_tests/feature_networks/old_api_test.py
As part of the rearrangement of the API, some non experimental APIs were removed. This commit revert this.
=> Add old APIs

model_compression_toolkit/core/keras/back2framework/instance_builder.py, model_compression_toolkit/core/keras/back2framework/keras_model_builder.py, model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py, model_compression_toolkit/exporter/model_exporter/keras/int8_tflite_exporter.py, model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py, model_compression_toolkit/exporter/model_wrapper/keras/validate_layer.py, tests/keras_tests/feature_networks_tests/feature_networks/activation_decomposition_test.py, tests/keras_tests/feature_networks_tests/feature_networks/bn_folding_test.py, tests/keras_tests/feature_networks_tests/feature_networks/conv_bn_relu_residual_test.py, tests/keras_tests/feature_networks_tests/feature_networks/experimental_exporter_test.py, tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_inputs_test.py, tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_test.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/change_qc_attr_test.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/edit_error_method_test.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/node_filter_test.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/keras_tests/feature_networks_tests/feature_networks/relu_replacement_test.py, tests/keras_tests/feature_networks_tests/feature_networks/shift_neg_activation_test.py, tests/keras_tests/feature_networks_tests/feature_networks/split_concatenate_test.py, tests/keras_tests/feature_networks_tests/feature_networks/symmetric_threshold_selection_activation_test.py, tests/keras_tests/feature_networks_tests/feature_networks/test_depthwise_conv2d_replacement.py, tests/keras_tests/feature_networks_tests/feature_networks/uniform_range_selection_activation_test.py, tests/keras_tests/function_tests/test_activation_quantization_holder_gptq.py, tests/keras_tests/layer_tests/base_keras_layer_test.py
1. Use a quantizer holder for activations instead of a wrapper during PTQ.
2. In the Keras model builder - replace layers wrapping using clone_model with building wrapped layers in OperationHandler.
3. Remove the Identity layer added for models to overcome the issue of quantizing inputs (now the holder quantizes it, and no wrapper is needed).
Exporter changes:
1. Update substitutions in Keras exporter (to stop handling activation quantizers in the wrapper and take input/output shapes from the wrapped layer since they are now inferred and not the internal layers).
2. Update the Keras validation function to consider new restrictions.
=> QI refactor for PTQ

model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py, tests/keras_tests/exporter_tests/test_runner.py, tests/keras_tests/exporter_tests/tflite_fake_quant/networks/conv2d_test.py, tests/keras_tests/exporter_tests/tflite_fake_quant/networks/dense_test.py, tests/keras_tests/exporter_tests/tflite_fake_quant/tflite_fake_quant_exporter_base_test.py
In TF export, as part of weights building of a layer, the attribute input_shape of the layer was searched. When a layer has multiple inbound layers with different shapes this is impossible. For this reason, we get the first input shape of the layer to support cases where multiple input shapes exist.
=> Fix tf export of reused layers

model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py, model_compression_toolkit/qat/keras/quantization_facade.py, tests/keras_tests/exporter_tests/test_runner.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/edit_error_method_test.py, tests/keras_tests/feature_networks_tests/feature_networks/symmetric_threshold_selection_activation_test.py, tests/keras_tests/function_tests/test_exporting_qat_models.py, tests/keras_tests/function_tests/text_exporting_qat_models.py
Two changes to support exporting QAT finalized models:
1. Creating new KerasActivationQuantizationHolder layers after converting the trainable quantizer to inferable. This is done to remove the training-related weights.
2. When creating an unwrap layer (during export), we create the weights based on the wrapped layer instead of going over the weights of the wrapped layer (which caused issues when the model was in eager mode).
=> Support export of QAT finalized models

model_compression_toolkit/exporter/model_exporter/keras/int8_tflite_exporter.py, tests/keras_tests/feature_networks_tests/feature_networks/experimental_exporter_test.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/keras_tests/function_tests/test_activation_quantization_holder_gptq.py
Remove the activation quantizers attribute from the Keras wrapper (since it was moved to KerasActivationQuantizationHolder previously).
=> Remove activation quantizers from KerasQuantizeWrapper

model_compression_toolkit/core/common/quantization/filter_nodes_candidates.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/lut_kmeans_params.py
Adding an additional filtering step to node candidates filtering, since after first filter we might get duplications in the remaining candidates (in specific mixed precision scenario that include LUT quantization option).
In addition, a small fix to LUT kmeans call is done to eliminate some sklearn's warning
=> Add final filtering phase to node candidates filtering

requirements.txt, tests/keras_tests/exporter_tests/tflite_fake_quant/networks/conv2d_test.py, tests/keras_tests/exporter_tests/tflite_int8/networks/dense_test.py, tests/keras_tests/function_tests/test_exporting_qat_models.py
Removing the restriction of numpy!=1.25.0 from the requirements.
The difference in new numpy versions is that it no longer returns 'False' when comparing np arrays of different shapes, but instead throws an exception.
This only required a small modification in several tests and didn't affect any of the actual code.
=> Remove restriction on numpy version in requirements

model_compression_toolkit/exporter/model_wrapper/keras/builder/node_to_quantizer.py
According to the MCT Quantizers type hint we expect the clusters centers to be a list of floats, but we export it a 2D array
=> Flatten cluster centers before building exportable model with LUT to get a list of clusters values instead of 2D array

model_compression_toolkit/constants.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/common/similarity_analyzer.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/keras_tests/function_tests/test_sensitivity_metric_interest_points.py
* Fixed softmax node type in MP-related nodes mapping functions.
*  Fix KL divergence computation per softmax activation axis.
* Fix other missing types in node mapping by type functions for mixed precision.
See:
https://app.clickup.com/t/860r59zcb
https://app.clickup.com/t/32wz4zf
=> Fix issues with softmax layer in mixed precision distance metric computation

.gitignore, tutorials/notebooks/example_pytorch_mobilenetv2_cifar100_mixed_precision.ipynb, tutorials/notebooks/example_pytorch_mobilenetv2_cifar100_mixed_precision.py
Add notebook to demonstrate quantizing mbv2 on cifar100 using mixed-precision.
Fixes to current example script:
1. Reducing eval batch size to 32
2. Setting seed to reproduce results
=> Add MP pytorch MBV2 cifar100 notebook

model_compression_toolkit/constants.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/kmeans_params.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/lut_kmeans_params.py, model_compression_toolkit/core/common/quantization/quantizers/kmeans_quantizer.py, model_compression_toolkit/core/common/quantization/quantizers/lut_kmeans_quantizer.py, model_compression_toolkit/core/common/quantization/quantizers/quantizers_helpers.py, model_compression_toolkit/core/keras/quantizer/lut_fake_quant.py, model_compression_toolkit/core/pytorch/quantizer/lut_fake_quant.py, model_compression_toolkit/exporter/model_wrapper/keras/builder/node_to_quantizer.py, model_compression_toolkit/exporter/model_wrapper/pytorch/builder/node_to_quantizer.py, model_compression_toolkit/target_platform_capabilities/target_platform/op_quantization_config.py, tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py, tests/keras_tests/function_tests/test_lut_activation_quanitzer_fake_quant.py, tests/keras_tests/function_tests/test_lut_activation_quanitzer_params.py, tests/keras_tests/function_tests/test_lut_quanitzer_params.py, tests/pytorch_tests/model_tests/feature_models/lut_quantizer_test.py
replace "multiplier_n_bits" to "lut_values_bitwidth" and "cluster_centers" to "lut_values" in lut related code to be compatible with MCTQ
=> Align LUT parameters names with MCTQ

.github/workflows/nightly.yml
Edit before building whl the requirements file to require mct-quantizers-nightly instead of mct-quantizers.
=> Fix mct-nightly requirements file

model_compression_toolkit/core/common/substitutions/shift_negative_activation.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/shift_negative_activation.py, tests/pytorch_tests/model_tests/feature_models/shift_negative_activation_test.py
In SNC, when better-shifting values are tested for a better choice, the histogram (which is a numpy object) is quantized using the non-linear node activation quantization function (to estimate the expected mse compared to the original histogram). The issue is that this quantization function is a framework tensor, which makes it fail since it expects a fw tensor. To overcome the issue, this commit adds to the common part of SNC an argument which is a callable that receives two arguments and returns one: it gets the fw activation quantization function and the bins to quantize. The function (of each fw) responsible for doing (if needed) a preprocessing and postprocessing to the bins, which is a numpy object.
Only if this function is passed - common SNC will use this function. If not - it …
=> Fix params search in pytorch SNC

model_compression_toolkit/core/common/node_prior_info.py, model_compression_toolkit/core/common/substitutions/shift_negative_activation.py
Add to NodePriorInfo a method to create a shifted version of it. Use it in SNC to attach prior info for new Add nodes.
=> Fix missing prior info for new nodes in SNC

tests/keras_tests/exporter_tests/tflite_fake_quant/tflite_fake_quant_exporter_base_test.py, tests/keras_tests/exporter_tests/tflite_int8/networks/mobilenetv2_test.py, tests/keras_tests/function_tests/test_exporting_qat_models.py
Remove predictions check in TF export tests.
The quantization parameters are asserted to be similar before and after export.
=> Fix exporter random tests

.github/workflows/link_checker.yml, model_compression_toolkit/core/keras/back2framework/mixed_precision_model_builder.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py, model_compression_toolkit/gptq/keras/gptq_training.py, model_compression_toolkit/gptq/keras/graph_info.py, model_compression_toolkit/gptq/keras/quantizer/base_keras_gptq_quantizer.py, model_compression_toolkit/gptq/keras/quantizer/soft_rounding/soft_quantizer_reg.py, model_compression_toolkit/qat/keras/quantization_facade.py, model_compression_toolkit/qat/keras/quantizer/ste_rounding/symmetric_ste.py, model_compression_toolkit/qat/keras/quantizer/ste_rounding/uniform_ste.py, model_compression_toolkit/trainable_infrastructure/keras/load_model.py, model_compression_toolkit/trainable_infrastructure/keras/quantize_wrapper.py, tests/doc_tests/test_docs_links.py, tests/keras_tests/feature_networks_tests/feature_networks/activation_decomposition_test.py, tests/keras_tests/feature_networks_tests/feature_networks/linear_collapsing_test.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/keras_tests/function_tests/test_activation_quantization_holder_gptq.py, tests/keras_tests/function_tests/test_gptq_soft_quantizer.py, tests/keras_tests/function_tests/test_set_layer_to_bitwidth.py, tests/keras_tests/function_tests/test_unsupported_custom_layer.py, tests/keras_tests/layer_tests/base_keras_layer_test.py, tests/keras_tests/models_tests/test_networks_runner.py, tests/keras_tests/models_tests/test_networks_runner_float.py, tests/trainable_infrastructure_tests/keras/base_keras_trainable_infra_test.py
1. Refactor the Keras quantization wrapper: create a Keras training that inherits from the MCTQ wrapper and handle the conversion to inferable quantizers correctly.
2. minor fix: use MCT Logger instead of MCTQ Logger
3. fix error message compare bug in keras custom layer test
=> refactor quantization wrapper for solving issue #787

model_compression_toolkit/core/common/mixed_precision/bit_width_setter.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
This PR fixes issue #820.
The issue occurs where there is a mixed precision run with mixed TPC, that is, a TPC that defines several quantization configs to one layer that has weights to quantize, and a single config to another layer that has weights to quantize.
The issue is in the bit width setter when finalizing the graph bitwidth.
In addition, adding a simple test that verifies that this issue is fixed.
=> Fix issue in finalize bitwidth with mixed configurations to weights layers in TPC

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/hessian/hessian_info_service.py, model_compression_toolkit/core/common/hessian/trace_hessian_calculator.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, model_compression_toolkit/core/runner.py, model_compression_toolkit/gptq/common/gptq_training.py
Fixes to the hessian refactor #823 
- Mixed precision: Added missing scores normalization.
- GPTQ: Added missing alpha param (set to 0).
- Modified logs to be more informative.
- Remove commented-out code.
- Add framework implementation method to create a dataset with a batch size of 1 (instead if inside the HessianServiceInfo).
=> Fix hessian refactor issues

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/hessian/hessian_info_service.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py
To avoid all possible types in the representative dataset (numpy array, tensorflow/pytorch tensors), the sampling method was moved to the hessian info service (instead of framework implementation) and changed to slice operation supported on these types of objects.
=> Move sampling a 1-batch to hessian info service

model_compression_toolkit/core/common/quantization/node_quantization_config.py, model_compression_toolkit/target_platform_capabilities/target_platform/op_quantization_config.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/qnnpack_tpc/v1/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/tflite_tpc/v1/tp_model.py, tests/common_tests/test_tp_model.py, tests/keras_tests/exporter_tests/tflite_int8/imx500_int8_tp_model.py, tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py, tests/keras_tests/function_tests/test_cfg_candidates_filter.py
Add simd_size for op configuration in the TPC.
For IMX500 TPCs: Ops with 8bits use SIMD 32, ops with 4bits use SIMD 64, and ops with 2bits use SIMD 128. In other TPCs it's set to None.
=> Add SIMD info to TPC

model_compression_toolkit/constants.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1/tpc_keras.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/tpc_keras.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/tpc_keras.py, tutorials/notebooks/example_keras_effdet_lite0.ipynb, tutorials/resources/efficientdet/__init__.py, tutorials/resources/efficientdet/effdet_keras.py, tutorials/resources/efficientdet/effnet_blocks_keras.py, tutorials/resources/efficientdet/effnet_keras.py, tutorials/resources/utils/__init__.py, tutorials/resources/utils/torch2keras_weights_translation.py, tutorials/resources/utils/weights_translation.py
This PR adds the code for porting the EfficientDet-lite0 pretrained model from [EffDet](https://github.com/rwightman/efficientdet-pytorch) to a keras model with a custom post-processing layer from [sony-custom-layer](https://github.com/sony/custom_layers).
Also added a tutorail notebook for porting the model and quantizing it with MCT
=> Add ported effdet keras tutorial

model_compression_toolkit/constants.py, model_compression_toolkit/core/common/hessian/hessian_info_utils.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_quantization_config.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/hessian/activation_trace_hessian_calculator_keras.py, model_compression_toolkit/core/keras/hessian/weights_trace_hessian_calculator_keras.py, model_compression_toolkit/core/pytorch/hessian/activation_trace_hessian_calculator_pytorch.py, model_compression_toolkit/core/pytorch/hessian/weights_trace_hessian_calculator_pytorch.py, model_compression_toolkit/gptq/__init__.py, model_compression_toolkit/gptq/common/gptq_config.py, model_compression_toolkit/gptq/common/gptq_training.py, tests/keras_tests/custom_layers_tests/test_sony_ssd_postprocess_layer.py, tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py, tests/keras_tests/function_tests/test_get_gptq_config.py, tests/keras_tests/function_tests/test_sensitivity_eval_non_suppoerted_output.py, tests/keras_tests/non_parallel_tests/test_keras_tp_model.py, tests/keras_tests/non_parallel_tests/test_lp_search_bitwidth.py, tests/keras_tests/non_parallel_tests/test_tensorboard_writer.py, tests/pytorch_tests/function_tests/test_sensitivity_eval_non_supported_output.py, tests/pytorch_tests/model_tests/feature_models/gptq_test.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py, tutorials/notebooks/example_keras_mobilenet_gptq_mixed_precision.py, tutorials/notebooks/example_keras_mobilenet_mixed_precision.py, tutorials/notebooks/example_keras_mobilenet_mixed_precision_lut.py, tutorials/notebooks/example_pytorch_mobilenet_mixed_precision.py, tutorials/notebooks/example_pytorch_mobilenet_mixed_precision_lut.py, tutorials/notebooks/example_pytorch_mobilenetv2_cifar100_mixed_precision.py
Modified names of Hessian-related variables and methods.
Removed any reference to "jacobians", "gradient-based" and "weights" in the scope of Hessian computation for mixed precision and gptq.
Replaced with uniform referencing as "**Hessian**-based **scores**", to prevent mixup with model's weights.
No functionality was affected in this changeset.
=> Hessian scores variables and methods names modification

model_compression_toolkit/core/common/defaultdict.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_weights_computation.py, model_compression_toolkit/core/keras/default_framework_info.py, model_compression_toolkit/core/pytorch/default_framework_info.py, model_compression_toolkit/gptq/keras/quantizer/ste_rounding/symmetric_ste.py, model_compression_toolkit/gptq/pytorch/quantizer/ste_rounding/symmetric_ste.py, tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py, tests/keras_tests/function_tests/test_get_gptq_config.py, tests/pytorch_tests/function_tests/get_gptq_config_test.py, tests/pytorch_tests/model_tests/feature_models/gptq_test.py
Fix FrameWorkInfo DefaultDict so MCT quantized model will work with torch.save
=> Fix issue #841: fix MCT so quantized models work with torch.save

model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py
This is a complementary fix for a missing piece from commit #850 .
Remove the output nodes from the list of interest points for MP metric.
=> Fix interest points list in MP to exclude outputs

model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_tflite_exporter.py
The Model Compression Toolkit appears to have a bug on Windows caused by trying to remove a file that is still open. Linux allows for deleting a file that is still open, but Windows is much more particular about this operation and in general trying to remove a file that is still open somewhere will result in a `PermissionError`. Here's a standalone reproduction of the fundamental problem:
```
PS C:\Users\James> py -3.9
Python 3.9.9 (tags/v3.9.9:ccb0e6a, Nov 15 2021, 18:08:50) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os, tempfile
>>> handle, tmpfile = tempfile.mkstemp()
>>> os.remove(tmpfile)  # File handle is still open, Windows will refuse to remove the file
Traceback (most recent call last):
File "<stdin>", …
```
=> Use context manager to avoid permission error on Windows

model_compression_toolkit/core/keras/hessian/activation_trace_hessian_calculator_keras.py, model_compression_toolkit/core/pytorch/hessian/activation_trace_hessian_calculator_pytorch.py
This is an unnecessary factor that remained from previous versions of the Hessian approximation method.
It doesn't affect the results of most common networks.
=> Remove constant multiplication factor from activation Hessian computation

model_compression_toolkit/core/graph_prep_runner.py, model_compression_toolkit/core/quantization_prep_runner.py, model_compression_toolkit/core/runner.py, tests/common_tests/helpers/prep_graph_for_func_test.py
This is part of a large refactor that will eventually split the main core runner into several runners, allowing more control over the specific quantization flow and method.
In this PR, all steps related to preparing the quantization information on the graph representation are extracted from the core runner to a dedicated "quantization preparation runner".
In addition, the PR includes minor documentation fixes to the graph preparation runner and the removal of duplicated functions.
=> Extract quantization preparation steps from core runner

model_compression_toolkit/core/common/similarity_analyzer.py, tests/keras_tests/function_tests/test_sensitivity_metric_interest_points.py
Add missing "axis" specification from the operation mean.
=> Fix KL-Divergence similarity function calculation

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/common/substitutions/batchnorm_folding.py, model_compression_toolkit/core/common/substitutions/batchnorm_reconstruction.py, model_compression_toolkit/core/common/substitutions/batchnorm_refusing.py, model_compression_toolkit/core/common/substitutions/linear_collapsing.py, model_compression_toolkit/core/common/substitutions/linear_collapsing_substitution.py, model_compression_toolkit/core/common/substitutions/residual_collapsing.py, model_compression_toolkit/core/graph_prep_runner.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/linear_collapsing.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/keras_tests/feature_networks_tests/feature_networks/linear_collapsing_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
Add a substitution for collapsing Op2d->add-const into the Op2d node
Op2d: Conv2D, DW-Conv2D, Conv2DTranspose or Dense
=> Add Op2d->add_const collapse substitution

model_compression_toolkit/core/keras/graph_substitutions/substitutions/activation_decomposition.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/matmul_substitution.py
This PR fixes a bug in the matmul-dense substitution (no "activation" attribute) and adds a warning to the ActivationDecomposition substitution to avoid this bug from recurring.
=> Fix activation in matmul sub

model_compression_toolkit/core/common/graph/base_graph.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_batch_norm.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
=> Adding functional batch_norm to BatchNorm2d substitution

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/keras_tests/function_tests/test_sensitivity_metric_interest_points.py
If the axis is not retrievable for the softmax operation, we can't compute kl-divergence correctly, so we use mse distance by default in mixed precision distance computation.
=> Set default distance function for softmax node in MP to be MSE if axis is not specified

model_compression_toolkit/core/keras/constants.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/activation_decomposition.py, tests/keras_tests/feature_networks_tests/feature_networks/activation_decomposition_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
In MP we need to know the axis used in Softmax for KL-Divergence computation. In activation decomposition, we created a simple 'Activation' layer thus we can not use the axis info when computing MP distance. This commit changes the decomposition to create a Softmax layer, thus enabling the KL-Divergence in MP distance computation.
=> Create Softmax layer in activation decomposition instead of Activation layer

model_compression_toolkit/qat/keras/quantizer/lsq/symmetric_lsq.py, model_compression_toolkit/qat/keras/quantizer/lsq/uniform_lsq.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
Add reshape to channel axis for LSQ QAT keras quantizers. This is needed for Conv-DW where we need to adapt the axis.
=> fix LSQ weights quantizer keras for dw-conv

model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py, model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_tflite_exporter.py
Add a verbose flag to FakelyQuantKerasExporter to avoid confusion in tflite export (since tflite fake quant export uses
an intermediate temp file that FakelyQuantKerasExporter produces).
=> Add verbose flag to FakelyQuantKerasExporter to avoid confusion in tflite export

tutorials/notebooks/example_keras_qat.py
Exporting non 8bits activation quantization in tflite is unsupported.
Thus, it's removed from qat tutorial.
=> Remove tflite export part from QAT tutorial

tutorials/notebooks/example_keras_imagenet.ipynb, tutorials/notebooks/example_keras_mobilenet_gptq.ipynb, tutorials/notebooks/example_keras_mobilenet_mixed_precision.ipynb
Tutorial/notebooks - Minor update to support notebook tests - a typo correction
=> Tutorial/notebooks - Minor update to support notebook tests - a typo correction

model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py
Change ONNX default opset when exporting Pytorch models. Changed from opset 16 to opset 17.
=> Change default onnx opset to 17

model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/common/graph/functional_node.py, model_compression_toolkit/core/keras/back2framework/keras_model_builder.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/linear_collapsing.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/matmul_substitution.py, model_compression_toolkit/core/keras/reader/node_builder.py, model_compression_toolkit/core/keras/tf_tensor_numpy.py, model_compression_toolkit/core/pytorch/back2framework/pytorch_model_builder.py, model_compression_toolkit/core/pytorch/constants.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/const_holder_conv.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_batch_norm.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_layer_norm.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, model_compression_toolkit/core/pytorch/reader/graph_builders.py, model_compression_toolkit/core/pytorch/reader/node_holders.py, model_compression_toolkit/ptq/pytorch/quantization_facade.py, tests/keras_tests/feature_networks_tests/feature_networks/const_representation_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/keras_tests/function_tests/test_unsupported_custom_layer.py, tests/pytorch_tests/layer_tests/base_pytorch_layer_test.py, tests/pytorch_tests/model_tests/base_pytorch_test.py, tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py, tests/pytorch_tests/model_tests/feature_models/bn_function_test.py, tests/pytorch_tests/model_tests/feature_models/const_representation_test.py, tests/pytorch_tests/model_tests/feature_models/layer_norm_net_test.py, tests/pytorch_tests/model_tests/feature_models/linear_collapsing_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
This PR refactors the way MCT handles constants. Instead of keeping them in the framework_attr, the constants are saved as weights in the internal graph nodes. The constants are referred to as "positional weights" whos keys are integers corresponding to the position of the constants in the call_args\call_kwargs. The constants are restored in the model builder.
This PR is the first step towards fully quantizing all constants in a model
=> Add constant weight representation in Keras & PyTorch

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1/tpc_pytorch.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/tpc_pytorch.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/tpc_pytorch.py
torch.squeeze shouldn't be quantized and is missing from the pytorch TPC no quantization list.
=> Add 'torch.squeeze' to list of NoQuantization operations in pytorch TPC

tests/trainable_infrastructure_tests/keras/trainable_keras/test_keras_base_quantizer.py, tests/trainable_infrastructure_tests/pytorch/trainable_pytorch/test_pytorch_base_quantizer.py
Fix base_quantizer tests after removing KMEANS QuantizationMethod from mctq.
Fix the expected error message since QuantizationMethod enum values were changed.
=> Fix base_quantizer tests

tests/keras_tests/feature_networks_tests/feature_networks/bn_attributes_quantization_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/pytorch_tests/model_tests/feature_models/bn_attributes_quantization_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Adding tests that enable Batchnorm layer attributes quantization to validate attributes quantization feature.
=> BN attributes quantization tests

tests/trainable_infrastructure_tests/keras/trainable_keras/test_keras_base_quantizer.py, tests/trainable_infrastructure_tests/pytorch/trainable_pytorch/test_pytorch_base_quantizer.py
Revert base_quantizer tests to use old MCTQ ENUM (with KMEANS) since testing on latest MCTQ and not nightly.
Added TODOs how to fix this tests when they fail next MCTQ release.
=> Revert KMEANS removel affected tests

model_compression_toolkit/core/common/quantization/quantization_params_generation/error_functions.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/power_of_two_selection.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_search.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/symmetric_selection.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/uniform_selection.py, model_compression_toolkit/core/common/similarity_analyzer.py
This PR removes the for loop for each threshold search per channel and uses numpy vectorization capability.
For KL divergence error function, we keep the loop because this KL involves histogram functions which are not trivial to vectorize.
=> Vectorized channel threshold search

.github/workflows/nightly.yml
Closes #998. 
This changeset modifies the nightly build workflow to set `model_compression_toolkit.__version__` in-source, making the full nightly version identifier available at runtime. This also resolves the curious post-release identifiers published to PyPI, which I assume were unintentional behavior (please correct me if I'm wrong).
=> Populate `__version__` for nightly builds

FAQ.md
replace link to html with link to exporter notebook
=> replace pytorch exporter example link

tutorials/notebooks/keras/ptq/example_keras_mobilenet_mixed_precision.ipynb
=> Fix resource utilization variable name in Keras tutorial

model_compression_toolkit/gptq/keras/quantization_facade.py
=> Fix missing resource utilization parameter in keras GPTQ facade

model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py
Adjust PyTorch's fakely_quant_onnx_pytorch_exporter to support exporting with custom quantizers for inner modules in the model instead of just for its children.
=> Fix PyTorch fakely_quant_onnx_pytorch_exporter

model_compression_toolkit/core/common/quantization/node_quantization_config.py, model_compression_toolkit/gptq/keras/gptq_training.py, model_compression_toolkit/gptq/pytorch/gptq_training.py
Fixing a bug added when attributes quantization was implemented, where after the GPTQ run the threshold parameter of the kernel was not updated correctly.
Also changing the argument names in set_quant_config_attr function, to prevent confusion.
=> Fix graph kernel attributes update after GPTQ run

model_compression_toolkit/core/common/quantization/quantization_params_generation/error_functions.py, tests/keras_tests/function_tests/test_kl_error_quantization_configurations.py, tests/keras_tests/function_tests/test_quantization_configurations.py, tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py, tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
KL error method per-tensor didn't work, and we didn't catch it since our selection tests didn't really run per-tensor tests as expected.
Also fixing other configuration tests that didn't check per-channel=False properly.
=> Fix KL error method per-tensor

model_compression_toolkit/target_platform_capabilities/target_platform/op_quantization_config.py
Make sure to update the weights attributes keys names in the TPC attributes config mapping.
=> Update base_config attributes names in TPC

model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_data.py, model_compression_toolkit/core/runner.py, tests/common_tests/helpers/generate_test_tp_model.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision/__init__.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision/requires_mixed_precision_test.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/keras_tests/non_parallel_tests/test_tensorboard_writer.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py, tests/pytorch_tests/model_tests/feature_models/qat_test.py, tests/pytorch_tests/tpc_pytorch.py
=> Add a flag to indicate whether to run mixed precision according to resource utilization provided by user.

model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py, model_compression_toolkit/exporter/model_exporter/pytorch/pytorch_export_facade.py, tests/pytorch_tests/exporter_tests/base_pytorch_export_test.py, tests/pytorch_tests/exporter_tests/base_pytorch_onnx_export_test.py, tests/pytorch_tests/exporter_tests/custom_ops_tests/test_export_pot_onnx_quantizers.py, tests/pytorch_tests/exporter_tests/custom_ops_tests/test_export_symmetric_onnx_quantizers.py
Fix an issue that imports onnx in the exporter during init if torch was found:
* In fakely_quant_onnx_pytorch_exporter.py, import onnx-related modules only if onnx was found. Add "dummy" FakelyQuantONNXPyTorchExporter to raise an error if it was used without Onnx installed.
* Move DEFAULT_ONNX_OPSET_VERSION to pytorch_export_facade.py to use it only there since it's in the pytorch_export_facade api.
=> Fix issue 1058

.github/workflows/nightly.yml, model_compression_toolkit/constants.py, model_compression_toolkit/data_generation/__init__.py, model_compression_toolkit/data_generation/pytorch/pytorch_data_generation.py
Fix an issue in importing torchvision during data generation init.
If torch was found and torchvision wasn't - an error was raised even when data generation wasn't used.
This PR fixes this, by checking it torchvision was also found.
In addition, after publishing the nightly package, it's tested that an import can be done after install tf and torch.
=> Fix torchvision import

tutorials/notebooks/imx500_notebooks/keras/example_keras_effdet_lite0_for_imx500.ipynb, tutorials/notebooks/imx500_notebooks/keras/example_keras_mobilenetv2_for_imx500.ipynb, tutorials/notebooks/imx500_notebooks/keras/example_keras_nanodet_plus_for_imx500.ipynb, tutorials/notebooks/imx500_notebooks/keras/keras_deeplabv3plus_for_imx500.ipynb, tutorials/notebooks/imx500_notebooks/keras/keras_yolov8n_for_imx500.ipynb, tutorials/notebooks/imx500_notebooks/pytorch/pytorch_mobilevit_xs_for_imx500.ipynb, tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb
=> Update the imx500 notebooks to install mct unless it's already installed

model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/ru_methods.py, model_compression_toolkit/core/common/statistics_correction/compute_bias_correction_of_graph.py, model_compression_toolkit/core/common/substitutions/residual_collapsing.py, model_compression_toolkit/core/pytorch/back2framework/instance_builder.py, model_compression_toolkit/core/pytorch/reader/graph_builders.py, tests/pytorch_tests/model_tests/feature_models/const_representation_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Enable constant values as inputs to linear layers in PyTorch
=> Enable constant values as inputs to linear layers in PyTorch

README.md
Change URLs in README from relative to absolute. This way, regardless of where the markdown is rendered (GitHub, PyPI), the links will always point to the correct resource.
=> Fix PyPI links

model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/pytorch/back2framework/pytorch_model_builder.py, tests/pytorch_tests/model_tests/feature_models/const_representation_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
The issue is that positional weights are only inserted as inputs to the node if the positional weights of the node are being quantized, and in any case where the node weights are not being quantized.
The PR addresses the scenario where the node weights are being quantized and the positional weights are not quantized.
=> Fix support const as input to linear layers in pytorch

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/keras_tests/function_tests/test_sensitivity_metric_interest_points.py
Use normalized MSE distance function in mixed precision sensitivity evaluation. For hessian-based sensitivity, simple MSE (not normalized) is used.
=> Use normalize MSE in mixed precision sensitivity evaluation

model_compression_toolkit/target_platform_capabilities/target_platform/op_quantization_config.py, tests/common_tests/helpers/generate_test_tp_model.py, tests/common_tests/test_tp_model.py, tests/keras_tests/feature_networks_tests/feature_networks/bias_correction_dw_test.py
Refactor QuantizationConfigOptions to enforce 'base_config' to be a different instance from the one in 'quantization_config_list'
=> Refactor QuantizationConfigOptions

tutorials/mct_model_garden/evaluation_metrics/coco_evaluation.py, tutorials/mct_model_garden/models_pytorch/yolov8/postprocess_yolov8_seg.py, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8-seg.yaml, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py, tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb, tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_seg_for_imx500.ipynb
Notebook utilities required for instance segmentation quantisation tutorial.
=> yolov8n Instance segmentation tutorial

model_compression_toolkit/core/common/hessian/hessian_info_service.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision/requires_mixed_precision_test.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/pytorch_tests/model_tests/base_pytorch_test.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Previous modification to Hessian service didn't handle the remaining samples correctly, allowing the representative dataset generator to terminate even if there were enough samples.
=> Fix Hessian batch sample method to use remaining samples correctly

tutorials/mct_model_garden/evaluation_metrics/coco_evaluation.py, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py, tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_seg_for_imx500.ipynb
Bug fix in the notebook's coco-evaluation functions.
=> Bug fix in the notebook's coco-evaluation functions.

tests/doc_tests/test_docs_links.py
Ignore base64-encoded image links, as they are valid inline images and don't need to be checked as external or local links.
=> Skip inline images in links checker test

model_compression_toolkit/core/common/graph/functional_node.py, model_compression_toolkit/core/pytorch/back2framework/pytorch_model_builder.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/const_holder_conv.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_batch_norm.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/functional_layer_norm.py, model_compression_toolkit/core/pytorch/reader/graph_builders.py, model_compression_toolkit/core/runner.py, model_compression_toolkit/target_platform_capabilities/target_platform/targetplatform2framework/operations_to_layers.py, tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py, tests/pytorch_tests/model_tests/feature_models/const_representation_test.py, tests/pytorch_tests/model_tests/feature_models/constant_conv_substitution_test.py, tests/pytorch_tests/model_tests/feature_models/layer_norm_net_test.py
Refactor includes:
1. remove duplication of framework_attr and node.kwargs in FunctionalNodes
2. reorder graph_builders.py
3. fix substitutions following the above changes
=> Refactor PyTorch model reader.

tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py
=> Remove todo as issue is currently not reproducible.

model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/common/graph/functional_node.py, model_compression_toolkit/core/keras/back2framework/keras_model_builder.py, model_compression_toolkit/core/keras/reader/node_builder.py, tests/keras_tests/feature_networks_tests/feature_networks/const_quantization_test.py, tests/keras_tests/feature_networks_tests/feature_networks/const_representation_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/keras_tests/non_parallel_tests/test_keras_tp_model.py
A small refactor to the Keras Node builder.
Two main modifications:
1. Remove hard-coded operator mapping and replace with tf.inspect to extract const weights from TFOpLambda layers.
2. Move the const extraction from op_call_args and op_call_kwargs to functions.
=> Keras node builder refactor

model_compression_toolkit/core/keras/reader/node_builder.py
Fixing the test to decide whether a function op layer receives the input as a list or not.
The current test checks to see if the first argument is a list, but some ops (like subtract) can receive the arguments as separate lists representing tensors. In this case, the inputs are not in a single list.
The solution is to manually check for inputs list only on specific operators that can get all inputs in a list.
=> Fix Keras input_as_list in node builder

tutorials/notebooks/mct_features_notebooks/keras/example_keras_mobilenet_gptq.ipynb, tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_mobilenet_gptq.ipynb
Improve gptq feature tutorials for keras and pytorch.
=> align torch and keras gptq tutorials

model_compression_toolkit/core/common/quantization/quantization_config.py, tests/pytorch_tests/model_tests/feature_models/qat_test.py
Update shift negative default setting to be enabled
=> Set default shift negative in quantization config

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_keras.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_pytorch.py
Add 16 bit input\output to `stack` & `concat` operators in TPC.v4
=> Add 16 bit input\output to stack & concat operators in TPC.v4

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_pytorch.py, tests/keras_tests/feature_networks_tests/feature_networks/activation_16bit_test.py, tests/pytorch_tests/model_tests/feature_models/activation_16bit_test.py
Add test for 16 bits for concat node.
Add `torch.concat` & `torch.concatenate` to TPC, as their types don't match `torch.cat`.
=> Add test for concat with 16 bit

model_compression_toolkit/core/common/quantization/bit_width_config.py, tests/keras_tests/feature_networks_tests/feature_networks/manual_bit_selection.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/pytorch_tests/model_tests/feature_models/manual_bit_selection.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Adding tests for Keras to check the manual bit width selection feature. In addition, added an informative message in the case that a node has an existing manual bit width configuration but a new manual configuration request of has been received, and the previous value is being overridden.
=> Tests for Keras to check the manual bit width selection feature.

model_compression_toolkit/core/common/mixed_precision/mixed_precision_candidates_filter.py, model_compression_toolkit/core/runner.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py, tests/pytorch_tests/model_tests/feature_models/qat_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
When running mixed precision quantization for weights/activation compression only but there are layers with multiple activation bit-width candidates, we need to filter out the irrelevant activation candidates (to make the layers non-configurable).
The same goes for activation only mixed precision.
For this, we added a new procedure before the mixed precision search which modified the candidates of the relevant nodes in the graph.
=> Filter out candidates for mixed precision in case of activation/weights only

model_compression_toolkit/core/keras/graph_substitutions/substitutions/conv_funcs_to_layer.py
Add LINEAR activation (i.e. no activation) to new Conv2D nodes.
=> Refactor TPC with supported input bit-width to each operator.

.github/workflows/test_whl_install.yml
Remove the tests running since this workflow's purpose is to check that it is possible to install MCT from its whl and import it.
=> update test whl workflow

tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py, tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb
Remove normalization from bounding box coordinates in yolov8n pytorch. (improved MAP accuracy)
=> Remove normalization from bounding box coordinates in yolov8n pytorch

tutorials/mct_model_garden/evaluation_metrics/anomaly_eval.py, tutorials/mct_model_garden/models_pytorch/Efficient_Anomaly_Det/efficient_ad.py, tutorials/notebooks/imx500_notebooks/pytorch/pytorch_efficient_anomaly_detection.ipynb, tutorials/resources/utils/efficient_ad_utils.py
Addition of anomaly detection model
=> efficient ad

tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_mobilenetv2_cifar100_mixed_precision.ipynb
New release changes some mixed precision argument name, so the tutorial which uses the latest release must be fixed.
=> Fix MP tutorial arguments after release

model_compression_toolkit/core/pytorch/reader/graph_builders.py
The PR addresses the case where a PyTorch graph contains additional input nodes, like `args` and `kwargs`, that have no outputs. Instead of causing an error, these nodes will be removed in the subsequent method: `remove_broken_nodes_from_graph`.
This PR includes a small update to the code that handles the extraction of `output_shape` based on the type of the `_node.meta[TYPE]`.
The old code assumes that `_node.meta[TENSOR_META]` is always present when` _node.meta[TYPE]` is a list or tuple. This assumption could lead to a `KeyError` if `TENSOR_META` is missing from `_node.meta.`
The new code uses `_node.meta.get(TENSOR_META, []) `instead, which returns an empty list if `TENSOR_META` is not found, thereby preventing potential errors and ensuring the code handles such cases more gracefully. …
=> Enhance Error Handling for TENSOR_META in Output Shape Calculation for YOLOv8 Quantization

model_compression_toolkit/gptq/pytorch/quantizer/quantization_builder.py, model_compression_toolkit/trainable_infrastructure/common/base_trainable_quantizer.py, model_compression_toolkit/trainable_infrastructure/pytorch/activation_quantizers/ste/symmetric_ste.py, model_compression_toolkit/trainable_infrastructure/pytorch/activation_quantizers/ste/uniform_ste.py, model_compression_toolkit/trainable_infrastructure/pytorch/base_pytorch_quantizer.py, tests/pytorch_tests/function_tests/test_activation_quantization_holder_gptq.py, tests/pytorch_tests/model_tests/feature_models/qat_test.py, tests/pytorch_tests/trainable_infrastructure_tests/base_pytorch_trainable_infra_test.py, tests/pytorch_tests/trainable_infrastructure_tests/test_pytorch_trainable_infra_runner.py, tests/pytorch_tests/trainable_infrastructure_tests/trainable_pytorch/test_pytorch_base_quantizer.py
Add freeze_quant_params flag to base trainable quantizer with False as default.
Implement quant params freezing for STE activation quantizers. 
Use activation trainable quantizers in GPTQ instead of inferable quantizers, with frozen quant params.
=> Fix activation gradient backprop in GPTQ

model_compression_toolkit/core/common/mixed_precision/mixed_precision_quantization_config.py, model_compression_toolkit/core/common/quantization/core_config.py, model_compression_toolkit/core/common/quantization/debug_config.py, model_compression_toolkit/core/common/quantization/quantization_config.py, model_compression_toolkit/core/common/substitutions/shift_negative_activation.py, model_compression_toolkit/core/runner.py, model_compression_toolkit/gptq/keras/quantization_facade.py, model_compression_toolkit/gptq/pytorch/quantization_facade.py, model_compression_toolkit/ptq/keras/quantization_facade.py, model_compression_toolkit/ptq/pytorch/quantization_facade.py, model_compression_toolkit/qat/keras/quantization_facade.py, model_compression_toolkit/qat/pytorch/quantization_facade.py, tests/common_tests/helpers/prep_graph_for_func_test.py, tests/keras_tests/feature_networks_tests/feature_networks/activation_16bit_test.py, tests/keras_tests/feature_networks_tests/feature_networks/const_quantization_test.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/edit_qc_test.py, tests/pytorch_tests/model_tests/feature_models/activation_16bit_test.py, tests/pytorch_tests/model_tests/feature_models/const_quantization_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Conver the following configuration classes to dataclasses and fix some misalignments in those classes: CoreConfig, QuantizationConfig, MixedPrecisionQuantizationConfig, DebugConfig, BitWidthConfig.
=> Set CoreConfig and its inner configs to be dataclasses

model_compression_toolkit/core/pytorch/reader/graph_builders.py, tests/pytorch_tests/model_tests/feature_models/activation_16bit_test.py
Fix PyTorch model reader for nodes with list input (e.g. `concat`), when both inputs are the same tensor (i.e. `concat([x, x], dim=2)`).
=> Fix PyTorch model reader

model_compression_toolkit/core/common/quantization/set_node_quantization_config.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/target_platform_capabilities.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/__init__.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_keras.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_pytorch.py, tests/keras_tests/feature_networks_tests/feature_networks/activation_16bit_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/pytorch_tests/model_tests/feature_models/activation_16bit_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
This PR handles quantization preservation in quantization options filtering. For example: in this network:
`add -> reshape -> conv`
the output of the add node can't have a 16 bit activation because the conv node doesn't support 16 bit inputs. reshape node is quantization preserving that supports both 8 and 16 bits.
=> Add TPC.v4 with quantization preservation.

model_compression_toolkit/core/pytorch/constants.py, model_compression_toolkit/core/pytorch/reader/graph_builders.py, tutorials/mct_model_garden/models_keras/efficientdet/LICENSE, tutorials/mct_model_garden/models_keras/efficientdet/effdet_keras.py, tutorials/mct_model_garden/models_keras/efficientdet/effnet_blocks_keras.py, tutorials/mct_model_garden/models_keras/efficientdet/effnet_keras.py, tutorials/mct_model_garden/models_keras/nanodet/LICENSE, tutorials/mct_model_garden/models_keras/nanodet/nanodet_keras_model.py, tutorials/mct_model_garden/models_keras/yolov8/LICENSE, tutorials/mct_model_garden/models_keras/yolov8/yolov8.py, tutorials/mct_model_garden/models_keras/yolov8/yolov8_preprocess.py, tutorials/mct_model_garden/models_keras/yolov8/yolov8n.yaml, tutorials/mct_model_garden/models_pytorch/mobilevit_xs/LICENSE, tutorials/mct_model_garden/models_pytorch/mobilevit_xs/mobilevit_xs.py, tutorials/mct_model_garden/models_pytorch/yolov8/LICENSE, tutorials/mct_model_garden/models_pytorch/yolov8/postprocess_yolov8_seg.py, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8-seg.yaml, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8_postprocess.py, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8_preprocess.py, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n-pose.yaml, tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n.yaml
Update license and copyright in the tutorials code
=> Tutorials license

model_compression_toolkit/trainable_infrastructure/pytorch/util.py
Change functools.cache to lru_cache, which is supported in python<3.9
=> change functools.cache to lru_cache

.github/workflows/run_pytorch_tests.yml, model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py, tests/pytorch_tests/exporter_tests/base_pytorch_onnx_export_test.py, tests/pytorch_tests/exporter_tests/test_onnx_multiple_inputs.py, tests/pytorch_tests/exporter_tests/test_onnx_multiple_inputs_and_outputs.py, tests/pytorch_tests/exporter_tests/test_onnx_multiple_outputs.py, tests/pytorch_tests/exporter_tests/test_runner.py
Add support for onnx export to models with multiple inputs/outputs.
=> Add support for onnx export to models with multiple inputs/outputs

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_keras.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_pytorch.py, tests/keras_tests/feature_networks_tests/feature_networks/const_quantization_test.py, tests/keras_tests/feature_networks_tests/feature_networks/const_representation_test.py
Support weight quantization for tf.gather in TPC imx500.v4. Currently only `params` may be a constant, and `indices` must be an input tensor.
=> Support weight quantization for tf.gather in TPC imx500.v4.

model_compression_toolkit/core/pytorch/back2framework/pytorch_model_builder.py, model_compression_toolkit/exporter/model_wrapper/pytorch/builder/fully_quantized_model_builder.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_pytorch.py, tests/pytorch_tests/model_tests/feature_models/const_quantization_test.py, tests/pytorch_tests/model_tests/feature_models/const_representation_test.py
Add const quantization for torch.gather ("params" attribute only).
=> Add const quantization for torch.gather ("params" attribute only).

model_compression_toolkit/core/common/hessian/__init__.py, model_compression_toolkit/core/common/hessian/hessian_info_service.py, model_compression_toolkit/core/common/hessian/hessian_scores_request.py, model_compression_toolkit/core/pytorch/hessian/activation_hessian_scores_calculator_pytorch.py, model_compression_toolkit/gptq/common/gptq_config.py, model_compression_toolkit/gptq/common/gptq_training.py, model_compression_toolkit/gptq/pytorch/gptq_loss.py, model_compression_toolkit/gptq/pytorch/gptq_training.py, model_compression_toolkit/gptq/pytorch/quantization_facade.py, model_compression_toolkit/gptq/pytorch/quantizer/regularization_factory.py, model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/soft_quantizer_reg.py, tests/pytorch_tests/model_tests/feature_models/gptq_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Add hessian estimation per image hash.
Add sample-layer attention distillation loss.
Add weights per layer to soft round loss.
Update GPTQ config and its generation for sample layer attention.
=> Add initial Sample-Layer Attention for GPTQ (PyTorch)

.github/workflows/run_tests_suite_coverage.yml
Use separate environments for coverage testing of Keras and Torch.
This fixes the issue of the flag "FOUND_TF" being set even if TF is uninstalled. The issue started with the start of pytest usage.
=> Fix coverage workflow

model_compression_toolkit/qat/keras/README.md, model_compression_toolkit/trainable_infrastructure/keras/README.md
Update READMEs of Keras QAT and trainable infra after moving quantizers from the QAT to trainable infra module.
=> Update READMEs after keras quantizers refactor

setup.py
tests_pytest is included in the wheel as it was not explicitly excluded from find_packages.
Use include instead of exclude in find_packages to automatically exclude any new non-product code.
=> fix package discovery for wheel

model_compression_toolkit/core/common/framework_implementation.py, model_compression_toolkit/core/common/quantization/node_quantization_config.py, model_compression_toolkit/core/common/quantization/quantization_config.py, model_compression_toolkit/core/common/statistics_correction/apply_activation_bias_correction_to_graph.py, model_compression_toolkit/core/common/statistics_correction/compute_activation_bias_correction_of_graph.py, model_compression_toolkit/core/common/statistics_correction/statistics_correction.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/core/keras/statistics_correction/keras_compute_activation_bias_correction_of_graph.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, model_compression_toolkit/core/pytorch/statistics_correction/pytorch_compute_activation_bias_correction_of_graph.py, model_compression_toolkit/core/runner.py, tests/keras_tests/feature_networks_tests/feature_networks/activation_bias_correction_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/pytorch_tests/model_tests/feature_models/activation_bias_correction_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Activation Bias Correction feature calculates the quantization error from activation quantization and "corrects" it in the next layer's bias.
The feature is set to False by default.
=> Add feature Activation Bias Correction

model_compression_toolkit/core/keras/graph_substitutions/substitutions/conv_funcs_to_layer.py, tests/keras_tests/feature_networks_tests/feature_networks/conv_func_substitutions_test.py, tests/keras_tests/feature_networks_tests/feature_networks/linear_collapsing_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py
Fixed tf conv substitution to handle attrs with default values that were not passed explicitly, and convert tf-specific format to keras compatible values.
=> fix tf.nn.{conv2d,convolution} substitution

model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/common/graph/functional_node.py
Fix duplicate QCOs error: raise error only if duplicate QCOs are not identical.
=> Fix duplicate QCOs issue

model_compression_toolkit/gptq/keras/quantization_facade.py, tests/keras_tests/function_tests/test_activation_quantization_holder_gptq.py
Enable SLA and gradual activation quantization by default in Keras.
=> Enable SLA by default in Keras

model_compression_toolkit/core/common/fusion/graph_fuser.py, model_compression_toolkit/core/common/graph/memory_graph/compute_graph_max_cut.py, model_compression_toolkit/core/common/mixed_precision/bit_width_setter.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_candidates_filter.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_data.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/ru_aggregation_methods.py, model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py, model_compression_toolkit/core/common/mixed_precision/solution_refinement_procedure.py, model_compression_toolkit/core/runner.py, tests/pytorch_tests/model_tests/feature_models/manual_bit_selection.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py
=> Just some cosmetics

requirements.txt
This fixes an issue with tensorboard when using this version of matplotlib.
See [this issue](https://github.com/RVC-Project/Retrieval-based-Voice-Conversion-WebUI/issues/2411)
=> restricting matplotlib to version < 3.10.0

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tp_model.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_keras.py, model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_pytorch.py
This PR moves splitting ops (e.g. split, unstack and slice) to a "qpreserving" opset. This opset disables activation quantiztion, enables quantization preserving and enables input & output tensors to be 16 bits.
This PR is compatible with the op definitions in the converter release 3.16.
=> Move splitting ops from default to qpreserving configs in TPCv4.

model_compression_toolkit/core/pytorch/back2framework/pytorch_model_builder.py
=> remove tpc from graph object saved in the output pytorch model

model_compression_toolkit/target_platform_capabilities/tpc_io_handler.py, tests/common_tests/test_tp_model.py, tests/test_suite.py
Added the 'load_target_platform_model' and 'export_target_platform_model' functions to import and export 'TargetPlatformModel' instances to JSON files with robust validation and error handling. It also includes comprehensive tests for both the 'export_target_platform_model' and 'load_target_platform_model' functions, covering valid use cases, edge cases, and error scenarios.
=> Added JSON import and export capabilities to TargetPlatformModel

model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/matmul_decomposition.py, model_compression_toolkit/core/pytorch/pytorch_implementation.py, tests/pytorch_tests/model_tests/feature_models/matmul_test.py, tests/pytorch_tests/model_tests/test_feature_models_runner.py
Add substitution to support MatMul function & operator by doing Reshape->Split->2D MatMul->Stack->Reshape
=> Pytorch MatMul Substitution

model_compression_toolkit/gptq/keras/quantization_facade.py, model_compression_toolkit/gptq/pytorch/quantization_facade.py, tutorials/notebooks/mct_features_notebooks/keras/example_keras_mobilenet_gptq.ipynb
Fix var name in gptq tutorial.
Fix setting default loss function in façades.
=> gptq fixes

model_compression_toolkit/core/keras/data_util.py, tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests_pytest/keras/core/test_data_util.py
The previous implementation of `FixedSampleInfoDataset` caused issues when working with models that expected multiple inputs with different shapes. Specifically, during inference it would raise a ValueError indicating a mismatch between the expected and received number of input tensors.
Instead of directly converting samples to tensors, we now separate the input tensors by their position in the input tuple, create a dictionary mapping each tensor position to its corresponding data, use tf.data.Dataset.from_tensor_slices with the dictionary structure and map the dictionary outputs back to the expected tuple format.
This preserves the tensor grouping and shapes while allowing different shapes for different input layers.
=> Refactor FixedSampleInfoDataset to Support Multi-Input Models

model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_calculator.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_data.py, model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py, model_compression_toolkit/core/runner.py, tests/common_tests/function_tests/test_resource_utilization_object.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
Report final resource utilization only for mixed precision constrained targets
=> Report final ru only for mixed precision constrained targets

model_compression_toolkit/core/keras/resource_utilization_data_facade.py, model_compression_toolkit/core/pytorch/resource_utilization_data_facade.py, model_compression_toolkit/gptq/keras/quantization_facade.py, model_compression_toolkit/gptq/pytorch/quantization_facade.py, model_compression_toolkit/pruning/keras/pruning_facade.py, model_compression_toolkit/pruning/pytorch/pruning_facade.py, model_compression_toolkit/ptq/keras/quantization_facade.py, model_compression_toolkit/ptq/pytorch/quantization_facade.py, model_compression_toolkit/qat/keras/quantization_facade.py, model_compression_toolkit/qat/pytorch/quantization_facade.py, model_compression_toolkit/target_platform_capabilities/tpc_io_handler.py, tests/common_tests/test_tpc.py
to manage TPC checking and allowing MCT to accept TPC as JSON
=> use load_target_platform_capabilities in all facades

model_compression_toolkit/core/common/graph/memory_graph/max_cut_astar.py, model_compression_toolkit/core/common/mixed_precision/solution_refinement_procedure.py
=> Fix MP refinement procedure

tutorials/notebooks/mct_features_notebooks/keras/example_keras_activation_threshold_search.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_activation_z_score_threshold.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_mobilenet_gptq.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_mobilenet_mixed_precision.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_network_editor.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_post-training_quantization.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_pruning_mnist.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_qat.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_xquant.ipynb
Add patch part to TF version in tutorials to make sure TF 2.14 is installed (without mentioning the patch version and using ~= in pip install, it kept the 2.17 version that is installed in the colab: https://stackoverflow.com/a/67374648/11404086). In addition, remove [and-cuda] to enable successful installation in colab.
=> Fix tf 2.14 installation in tutorials

model_compression_toolkit/data_generation/pytorch/optimization_functions/image_initilization.py, requirements.txt
=> Remove opencv dependency and replace with torch logic.

model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py
Adding LP constraints for Activation modifies its LP term, which is also used for the Total target. If Activation constraints is added before the Total, the constraint for Total is wrong (by +activation RU target). The failure is intermittent since the targets are kept in a set, so the order is not fixed. 
This PR is a temporary fix that makes sure that Total constraints are added before the Activation constraints.
=> Fix intermittent bug in MP LP definition when both total and activation targets are constrained

model_compression_toolkit/target_platform_capabilities/tpc_models/tflite_tpc/v1/tpc.py
Fixed bug in TFLite TPC regarding the quantization of kernels in conolutions and linear layers.
=> Fixed bug in TFLite TPC

model_compression_toolkit/core/common/graph/memory_graph/compute_graph_max_cut.py, model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/scaled_dot_product_attention.py
Fixed bug in ScaledDotProductDecomposition substitution regarding how output_shapes of nodes are calculated.
=> Fix bug that caused ViT models to raise errors.

model_compression_toolkit/core/common/graph/memory_graph/cut.py, model_compression_toolkit/core/common/graph/memory_graph/max_cut_astar.py, tests/keras_tests/function_tests/test_graph_max_cut.py
Add cut's sorted node names list to sort key, so that same cuts are returned between different runs (not necessarily in the same order).
=> Deterministic max cut

.github/workflows/run_pytorch_tests.yml, .github/workflows/run_tests_suite_coverage.yml
Due to https://github.com/microsoft/onnxruntime-extensions/issues/910
=> Temporarily limit onnxruntime-extensions<0.14 in tests

tests_pytest/keras_tests/e2e_tests/post_training_quantization_tests/__init__.py, tests_pytest/keras_tests/e2e_tests/post_training_quantization_tests/test_quantization_methods.py, tests_pytest/keras_tests/e2e_tests/test_post_training_quantization.py
=> Adding integration tests package with ptq e2e test example and converting symmetric selection unit test to pytest

model_compression_toolkit/core/common/graph/base_graph.py, model_compression_toolkit/core/common/graph/base_node.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_ru_helper.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_facade.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_calculator.py, model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py, model_compression_toolkit/core/common/mixed_precision/solution_refinement_procedure.py, tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py, tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py, tests/keras_tests/non_parallel_tests/test_lp_search_bitwidth.py, tests/keras_tests/non_parallel_tests/test_tensorboard_writer.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py, tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py, tests/pytorch_tests/model_tests/feature_models/qat_test.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/test_greedy_solution_refinement.py
- Simplify resource utilization constraints construction - compute total weights/bops directly instead of per node and aggregating at a later stage. Use RUCalculator to compute all targets at once and use the results directly. Remove separate computation for non-configurable nodes. Remove all intermediate methods per target and the double api for conf/non-conf which are no longer needed. Remove special hacky handling of total ru metric, which is now obtained automatically by RUCalculator along with the rest.
- Convert LP solver module functions into class, remove dependency on MPSearchManager, move all code that is not related to LP to MPSearchManager.
- Move more of MP search responsibility to MPSearchManager and make it the entry point for the search. The manager precomputes all metrics …
=> MP cleanup and partial refactoring

model_compression_toolkit/core/common/graph/virtual_activation_weights_node.py, tests_pytest/_test_util/graph_builder_utils.py, tests_pytest/common_tests/unit_tests/core/graph/__init__.py, tests_pytest/common_tests/unit_tests/core/graph/test_virtual_activation_weights_node.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/resource_utilization_tools/test_resource_utilization_calculator.py, tests_pytest/common_tests/unit_tests/test_model_collector.py
When creating the combined virtual node, weights from both activation and weights nodes are taken, as long as only the weights node contains kernel, so that weight utilization is computed correctly. If was assumed and validated that the activation node doesn't contain same weight attributes as the weights node, which is wrong, e.g. layer norm in torch contains weight and bias, same as conv.
This PR fixes this case. If activation and weight nodes contain duplicate weight attribute or index, a new unique name or index is created for the activation node and node's quantization cfg attribute and positional dicts are updated accordingly.
=> Fix virtual node construction with duplicate weights attributes

model_compression_toolkit/gptq/common/gptq_config.py
This small PR corrects validation error messaging in the `QFractionLinearAnnealingConfig` class. The PR fixes two issues:  
- **Missing f-string formatting**: Added proper string interpolation to display actual `end_step` and `start_step` values.  
- **Typo in error message variable**: Corrected `start_stap` to `start_step` to match the actual parameter name, preventing a runtime error.
=> Fix error message formatting in configuration validation

model_compression_toolkit/target_platform_capabilities/schema/v2.py
=> Add exp to schema v2

model_compression_toolkit/core/common/graph/base_graph.py, model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py, model_compression_toolkit/core/common/quantization/set_node_quantization_config.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests_pytest/common_tests/unit_tests/core/graph/test_node_quantization.py, tests_pytest/common_tests/unit_tests/core/graph/test_quantization_preserving_node.py
Handle quantization preserving nodes that have more than 1 input, or come after an unquantized node. For these nodes, quantization preserving is disabled.
=> Handle quantization preserving with 2 inputs

model_compression_toolkit/core/common/quantization/bit_width_config.py, tests_pytest/pytorch_tests/e2e_tests/test_weights_manual_selection_bitwidth.py, tests_pytest/pytorch_tests/integration_tests/core/quantization/test_set_node_quantization_config.py
=> Add tests for manual bit width config for postional weights

model_compression_toolkit/core/common/quantization/set_node_quantization_config.py, model_compression_toolkit/core/common/substitutions/shift_negative_activation.py, tests_pytest/common_tests/unit_tests/core/graph/test_node_quantization.py
Filter out nodes without enable quantization and not preserving
=> Node Supported Bitwidth Filtering Bugfix

model_compression_toolkit/core/common/graph/virtual_activation_weights_node.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py, model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_calculator.py, tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_bops_test.py, tests/keras_tests/function_tests/test_weights_activation_split_substitution.py, tests_pytest/_fw_tests_common_base/base_ru_integration_test.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/resource_utilization_tools/test_resource_utilization_calculator.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/test_mp_search_manager.py, tests_pytest/keras_tests/integration_tests/core/mixed_precision/test_resource_utilization.py, tests_pytest/pytorch_tests/integration_tests/core/mixed_precision/test_resource_utilization.py
* Rewrite virtual config reconstruction helper. Add support for separate configuration for activation and weights, in preparation for float mp baseline model - so that we can quantize layers activation only or weights only, even though candidates quantize both.
* Remove activation candidates from virtual weights split node (it was a hack needed when computing RU on virtual graph, which is not done anymore).
* Remove support for virtual graph from RU calculator, enable calculating bops for case when input activation has multiple outputs (still results in underestimation, but less so).
=> Refactor virtual config reconstruction helper, support separate configuration for activations and weights

model_compression_toolkit/core/common/mixed_precision/mixed_precision_quantization_config.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_facade.py, model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py, model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py, model_compression_toolkit/core/common/mixed_precision/set_layer_to_bitwidth.py, model_compression_toolkit/core/common/mixed_precision/solution_refinement_procedure.py, model_compression_toolkit/core/common/quantization/node_quantization_config.py, model_compression_toolkit/core/common/similarity_analyzer.py, model_compression_toolkit/core/keras/back2framework/mixed_precision_model_builder.py, model_compression_toolkit/core/pytorch/back2framework/mixed_precision_model_builder.py, tests_pytest/_fw_tests_common_base/base_sensitivity_eval_integ_test.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/test_custom_metric_function.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/test_mp_search_manager.py, tests_pytest/keras_tests/integration_tests/core/mixed_precision/test_sensitivity_evaluation.py, tests_pytest/keras_tests/keras_test_util/keras_test_mixin.py, tests_pytest/pytorch_tests/integration_tests/core/mixed_precision/test_sensitivity_evaluation.py, tests_pytest/pytorch_tests/torch_test_util/torch_test_mixin.py
* Use float mp model baseline instead of maxbit configuration
* Add unit test for MPSearchManager sensitivity matrix building
* Add integration tests for SensitivityEvaluation quant layers and quantizers configuration
* Ensure positive value in shifted cosine similarity metric (if it's negative due to float precision lp program is unbounded). 
* Fix refinement solutions unreadable (by recent change) printout, and only print the changed solutions
=> Use float mp model baseline instead of maxbit configuration

.github/workflows/link_checker.yml, README.md, model_compression_toolkit/ptq/keras/quantization_facade.py, model_compression_toolkit/qat/keras/quantization_facade.py, model_compression_toolkit/qat/pytorch/quantization_facade.py, model_compression_toolkit/target_platform_capabilities/README.md, tutorials/notebooks/mct_features_notebooks/keras/example_keras_activation_threshold_search.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_activation_z_score_threshold.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_mobilenet_mixed_precision.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_post-training_quantization.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_pruning_mnist.ipynb, tutorials/notebooks/mct_features_notebooks/keras/example_keras_qat.ipynb, tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_activation_threshold_search.ipynb, tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_activation_z_score_threshold.ipynb, tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_data_generation.ipynb, tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_mixed_precision_ptq.ipynb, tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_post_training_quantization.ipynb
=> Update repo name string in links checker

tests_pytest/common_tests/unit_tests/core/graph/test_base_node.py, tests_pytest/common_tests/unit_tests/core/graph/test_node_quantization.py, tests_pytest/common_tests/unit_tests/core/graph/test_quantization_preserving_node.py, tests_pytest/common_tests/unit_tests/core/graph/test_virtual_activation_weights_node.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/resource_utilization_tools/test_resource_utilization_calculator.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/resource_utilization_tools/test_resource_utilization_data.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/sensitivity_eval/test_distance_calculator.py, tests_pytest/common_tests/unit_tests/core/mixed_precision/test_mp_search_manager.py, tests_pytest/common_tests/unit_tests/core/test_fusion_info.py, tests_pytest/common_tests/unit_tests/test_model_collector.py, tests_pytest/conftest.py
Switch pytest unittests to fw_info patch instead of changing the global _current_framework_info state.
Remove activation_quantizer_mapping from DummyFrameworkInfo in tests.
=> Refactor fw_info handling in pytest unittests

model_compression_toolkit/core/common/quantization/node_quantization_config.py, model_compression_toolkit/core/common/quantization/quantization_config.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_activations_computation.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_computation.py, model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_weights_computation.py, model_compression_toolkit/core/common/statistics_correction/apply_bias_correction_to_graph.py, model_compression_toolkit/core/common/statistics_correction/compute_bias_correction_of_graph.py, model_compression_toolkit/core/common/statistics_correction/statistics_correction.py, model_compression_toolkit/core/common/substitutions/batchnorm_reconstruction.py, model_compression_toolkit/core/graph_prep_runner.py, model_compression_toolkit/core/keras/graph_substitutions/substitutions/input_scaling.py, model_compression_toolkit/core/keras/keras_implementation.py, model_compression_toolkit/trainable_infrastructure/common/get_quantizer_config.py, model_compression_toolkit/trainable_infrastructure/common/trainable_quantizer_config.py, model_compression_toolkit/trainable_infrastructure/keras/config_serialization.py, tests/keras_tests/feature_networks_tests/feature_networks/network_editor/edit_qc_test.py, tests/keras_tests/feature_networks_tests/feature_networks/test_kmeans_quantizer.py, tests/keras_tests/feature_networks_tests/test_features_runner.py, tests/keras_tests/function_tests/test_gptq_soft_quantizer.py, tests/keras_tests/function_tests/test_node_quantization_configurations.py, tests/keras_tests/non_parallel_tests/test_lp_search_bitwidth.py, tests/keras_tests/trainable_infrastructure_tests/base_keras_trainable_infra_test.py, tests/keras_tests/trainable_infrastructure_tests/trainable_keras/test_keras_base_quantizer.py, tests/pytorch_tests/function_tests/test_gptq_soft_quantizer.py, tests/pytorch_tests/trainable_infrastructure_tests/base_pytorch_trainable_infra_test.py, tests/pytorch_tests/trainable_infrastructure_tests/trainable_pytorch/test_pytorch_base_quantizer.py
*Breaking change:* removed min_threshold from QuantizationConfig.
Remove the temporary patch that injected fields previously read from QuantizationConfig back into NodeWeightsQuantizationConfig and WeightsAttrQuantizationConfig.
Pass QuantizationConfig or its relevant field(s) instead of getting it from the node.
Second moment correction: for now keep weights_second_moment_correction flag in NodeWeightsQuantizationConfig, as it is used to mark the nodes for which to apply the correction and remove the reconstructed BN, but instead of reading from QuantizationConfig, set it in BN reconstruction substitution.
Bias correction:  remove weights_bias_correction flag from NodeWeightsQuantizationConfig. bias_corrected field is still injected into the config, use it instead to determine whether …
=> Node weights and node weights attr quantization configs clean-up - remove temporary patch for fields from QuantizationConfig

model_compression_toolkit/core/common/model_collector.py, tests_pytest/common_tests/unit_tests/test_model_collector.py
Fix channel axis init for collectors when a collection if required for the input of a node and previous node doesn't need collector (i.e. Dropout->Linear).
=> Fix channel axis init for collectors

requirements.txt
* limit pydantic version(<2.12.0)
* Added restrictions to MCT requirements due to usage of functions not supported in pydantic 2.12.0.
=> [RedSuns Review]limit pydantic version(<2.12.0)

requirements.txt
* limit pydantic version(<2.12.0)
* Added restrictions to MCT requirements due to usage of functions not supported in pydantic 2.12.0(2025/10/08 Release).
=> [SSS Review]limit pydantic version(<2.12.0)
