.github/labeler.yml
.github/workflows/label.yml
.github/workflows/test_feature_networks.yml

Two workflows are added:
1. Workflow to tag pull requests by the package that was changed: tests, common or keras.
2. Workflow to run all feature networks tests upon a pull request to the main branch.

Add workflows for github actions

---

setup.py

Update package name, description and classifiers in setup.py.

Fix setup file

---

requirements.txt

Use any version of Tensorflow 2.5, instead of 2.5.0

Update the requirements file

---

.github/workflows/publish_release.yml

Change the release workflow to not push a tag.

Remove tag pusshing from release workflow

---

.github/workflows/nigthly.yml

Changed nightly workflow to stop running for forks.

Fix nightly workflow

---

.github/workflows/run_tests_suite.yml
.github/workflows/run_tests_suite_tf26.yml
.github/workflows/run_tests_suite_tf27.yml

In nightly tests, fix indentation to schedule them nigthly.

Fix scheduling nightly tests

---

tests/keras_tests/function_tests/test_lp_search_bitwidth.py
tests/keras_tests/graph_tests/test_graph_collection.py
tests/keras_tests/graph_tests/test_graph_quantization_and_export.py

Fixed graph tests after refactor of supporting multiple frameworks.

Fix graph tests

---

model_compression_toolkit/common/quantization/set_node_quantization_config.py

Fix bug in setting the quantization flag in nodes' configurations that misused the framework info's groups.

Fix bug in creating nodes QC

---

model_compression_toolkit/common/collectors/mean_collector.py
model_compression_toolkit/common/collectors/min_max_per_channel_collector.py
model_compression_toolkit/common/collectors/statistics_collector.py
model_compression_toolkit/common/constants.py
model_compression_toolkit/common/framework_info.py
model_compression_toolkit/common/quantization/node_quantization_config.py
model_compression_toolkit/common/quantization/quantization_params_generation/qparams_activations_computation.py
model_compression_toolkit/common/quantization/quantization_params_generation/qparams_computation.py
model_compression_toolkit/keras/back2framework/model_builder.py
model_compression_toolkit/keras/default_framework_info.py
model_compression_toolkit/keras/graph_substitutions/substitutions/shift_negative_activation.py
model_compression_toolkit/keras/keras_model_validation.py
model_compression_toolkit/keras/quantizer/fake_quant_builder.py
model_compression_toolkit/keras/quantizer/gradient_ptq/activation_quantizer.py
model_compression_toolkit/keras/quantizer/gradient_ptq/activation_quantizer_gptq_config.py
model_compression_toolkit/keras/quantizer/gradient_ptq/activation_weight_quantizer_gptq_config.py
model_compression_toolkit/keras/quantizer/gradient_ptq/config_factory.py
tests/common_tests/function_tests/test_collectors_manipulation.py

This commit moves the activation quantization 'is_signed' flag
into the qparams dictionary, and creates an Enum to specify the
output channel index to be NHWC or NCHW.

Refactor qparams and output channel index

---

model_compression_toolkit/common/substitutions/batchnorm_folding.py
model_compression_toolkit/keras/graph_substitutions/substitutions/batchnorm_folding.py
model_compression_toolkit/keras/keras_implementation.py
model_compression_toolkit/pytorch/graph_substitutions/substitutions/batchnorm_folding.py
model_compression_toolkit/pytorch/pytorch_implementation.py
tests/common_tests/base_test.py

Fixed bug in the BaseTest in generating quantization configurations.

Moved duplicate code in batchnorm_folding subsitution to common.

---

model_compression_toolkit/common/graph/graph_matchers.py

Remove import of tensorflow in common file graph_matchers.
Fix type hints that used this import.

Fix import in graph_matchers

---

model_compression_toolkit/common/framework_implementation.py
model_compression_toolkit/common/gptq/gptq_config.py
model_compression_toolkit/common/mixed_precision/mixed_precision_quantization_config.py
model_compression_toolkit/common/post_training_quantization.py
model_compression_toolkit/keras/back2framework/model_builder.py
model_compression_toolkit/keras/gradient_ptq/training_wrapper.py
model_compression_toolkit/keras/keras_implementation.py
model_compression_toolkit/keras/quantizer/gradient_ptq/activation_weight_quantizer_gptq_config.py
model_compression_toolkit/keras/quantizer/gradient_ptq/config_factory.py
model_compression_toolkit/keras/quantizer/gradient_ptq/weight_quantizer.py
model_compression_toolkit/keras/quantizer/gradient_ptq/weight_quantizer_gptq_config.py

1. Enable different max change lsb for each bit-width.
2. Enable bias correction with GPTQ to improve initial training point.
3. Add Mixed-precision API config override option for bug.

Upgrade GPTQ

---

model_compression_toolkit/__init__.py
model_compression_toolkit/common/mixed_precision/sensitivity_evaluation_manager.py
model_compression_toolkit/pytorch/back2framework/model_builder.py
model_compression_toolkit/pytorch/mixed_precision/__init__.py
model_compression_toolkit/pytorch/mixed_precision/mixed_precision_wrapper.py
model_compression_toolkit/pytorch/mixed_precision/sensitivity_evaluation.py
model_compression_toolkit/pytorch/pytorch_implementation.py
model_compression_toolkit/pytorch/quantization_facade.py
tests/pytorch_tests/model_tests/base_pytorch_test.py
tests/pytorch_tests/model_tests/feature_models/mixed_precision_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Mixed Precision implementation for Pytorch framework:
- New wrapper class `PytorchMixedPrecisionWrapper` which allows configuring a Pytroch module (a layer in the model) with different values of bit-width.
- Modify `model_builder` which allows creating a MP model from a graph, such that each configurable layer in the model is wrapped with a `PytorchMixedPrecisionWrapper`.
- Dedicated sensitivity evaluation method for MP with Pytorch framework.
- In addition, functionalities that are shared for both Pytorch and TensorFlow were extracted to a common environment, under the new class `SensitivityEvaluationManager`, which maintains all necessary data and objects for running sensitivity evaluation during MP search.

Pytorch implementation for Mixed Precision

---

model_compression_toolkit/keras/default_framework_info.py

remove duplicate Dot from ACTIVATION list in keras default_framewotk_info

remove suplicate Dot

---

model_compression_toolkit/keras/default_framework_info.py

Added LayerNormalization to keras/default_framework_info ACTIVATION so it will be quantized

Add keras LayerNormalization quantization

---

model_compression_toolkit/keras/keras_node_prior_info.py
model_compression_toolkit/pytorch/pytorch_node_prior_info.py
tests/keras_tests/function_tests/test_bn_info_collection.py
tests/pytorch_tests/function_tests/bn_info_collection_test.py

fix bn info std update

---

model_compression_toolkit/hardware_models/keras_hardware_model/keras_default.py
model_compression_toolkit/hardware_models/keras_hardware_model/keras_qnnpack.py
model_compression_toolkit/hardware_models/keras_hardware_model/keras_tflite.py
tests/keras_tests/test_keras_hardware_model.py

Fix Tensorflow imports of layers between versions in framework-hardware-model
models of Tensorflow.

Fix TF imports in hardware-model files

---

model_compression_toolkit/common/gptq/gptq_config.py
model_compression_toolkit/keras/gradient_ptq/gptq_loss.py
model_compression_toolkit/keras/gradient_ptq/graph_info.py
model_compression_toolkit/keras/gradient_ptq/training_wrapper.py

Add 2 list to GPTQ loss API: mean % std of batch normalization information, if exists.

add model batch normalization info (mean & std) to GPTQ loss API

---

model_compression_toolkit/common/graph/base_graph.py
model_compression_toolkit/common/graph/base_node.py
model_compression_toolkit/common/quantization/node_quantization_config.py

First step in implementation of activation mixed-precision.
Preparing the graph and node configuration to support activation mp.

Activation mixed-precision configurations support 

---

model_compression_toolkit/common/substitutions/shift_negative_activation.py
tests/keras_tests/feature_networks_tests/feature_networks/shift_neg_activation_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

Fix in shift negative correction post_add node num_bits

---

tests/keras_tests/feature_networks_tests/feature_networks/scale_equalization_test.py

Define weight initialization to avoid zero valued weight (which as a result will lead to inability to calculate scale equalization)

Fix keras scale equalization tests

---

.github/workflows/label.yml

Changed label.yml to label PRs by the number of lines
changes, and warn about XL PRs.

Label PRs with size

---

model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_default.py
model_compression_toolkit/pytorch/utils.py

[Pytorch] Fixed small bug in torch_tensor_to_numpy function

[Pytorch] Added operator "torch.chunk" to "no quantization" list.

---

model_compression_toolkit/keras/constants.py
model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py

MHA node decomposition update: implement MHA iterations with layers reuse instead of folding the iterations to batch

Mha decomposition update

---

model_compression_toolkit/common/constants.py
model_compression_toolkit/common/graph/base_graph.py
model_compression_toolkit/common/graph/base_node.py
model_compression_toolkit/common/mixed_precision/kpi.py
model_compression_toolkit/common/mixed_precision/kpi_aggregation_methods.py
model_compression_toolkit/common/mixed_precision/kpi_methods.py
model_compression_toolkit/common/mixed_precision/mixed_precision_search_facade.py
model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py
model_compression_toolkit/common/mixed_precision/search_methods/linear_programming.py
tests/keras_tests/function_tests/test_lp_search_bitwidth.py

Generalize the KPI computation to allow support different weights and activation KPI methods.
KPI computation is now composed from an external-provided KPI computation function and KPI aggregation function.
The refactor implies changes in MixedPrecisionSearchModel (which is now responsible for most of the components needed in order to construct the LP search problem) and in the LP formalization implementation.

Mixed precision KPI metrics refactor

---

model_compression_toolkit/common/post_training_quantization.py
model_compression_toolkit/pytorch/graph_substitutions/substitutions/reshape_with_static_shapes.py
model_compression_toolkit/pytorch/pytorch_implementation.py
model_compression_toolkit/pytorch/reader/graph_builders.py
tests/pytorch_tests/model_tests/feature_models/dynamic_size_inputs_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

[Pytorch] Added new substitution, 'reshape_with_static_shapes', for 'reshape' and 'view' operators
[Pytorch] Added a test for the 'reshape_with_static_shapes' substitution.
[common] Fixed some comments

[Pytorch] Added new substitution, 'reshape_with_static_shapes'

---

tests/pytorch_tests/model_tests/base_pytorch_test.py
tests/pytorch_tests/model_tests/feature_models/dynamic_size_inputs_test.py
tests/pytorch_tests/model_tests/feature_models/torch_tensor_attr_net_test.py
tests/pytorch_tests/model_tests/model_zoo_tests/base_model_test.py
tests/pytorch_tests/model_tests/test_models_runner.py
tests/test_suite.py

* A small update for using the 'convert_to_fx' flag
* Added network tests
* Updated the test suite file

[Pytorch] Updated the tests:

---

model_compression_toolkit/common/graph/base_node.py
tests/keras_tests/function_tests/test_kpi_data.py
tests/pytorch_tests/function_tests/kpi_data_test.py

remove batch size from product

minor fix in output size computation

---

model_compression_toolkit/keras/quantization_facade.py
model_compression_toolkit/pytorch/quantization_facade.py

fix api_change PR: mixed precision config lass check

fix api_change PR

---

model_compression_toolkit/common/quantization/core_config.py
model_compression_toolkit/common/quantization/debug_config.py

Add missing license at beginning of files

Add license to core_config.py & debug_config.py

---

model_compression_toolkit/keras/constants.py
model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py

move keras Reshape attribute "target_shape" to constants.py

move keras Reshape attribute "target_shape" to constants.py

---

model_compression_toolkit/common/framework_implementation.py
model_compression_toolkit/common/post_training_quantization.py
model_compression_toolkit/common/quantization/quantization_config.py
model_compression_toolkit/common/substitutions/linear_collapsing_substitution.py
model_compression_toolkit/common/substitutions/residual_collapsing.py
model_compression_toolkit/keras/graph_substitutions/substitutions/residual_collapsing.py
model_compression_toolkit/keras/keras_implementation.py
model_compression_toolkit/pytorch/graph_substitutions/substitutions/residual_collapsing.py
model_compression_toolkit/pytorch/pytorch_implementation.py
tests/keras_tests/feature_networks_tests/feature_networks/residual_collapsing_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/residual_collapsing_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Support collapsing add residual to Conv2D layer.
Keras+Pytorch.

Add residual collapsing of Conv2D

---

model_compression_toolkit/common/mixed_precision/kpi.py
model_compression_toolkit/common/mixed_precision/kpi_aggregation_methods.py
model_compression_toolkit/common/mixed_precision/kpi_data.py
model_compression_toolkit/common/mixed_precision/kpi_methods.py
model_compression_toolkit/common/mixed_precision/mixed_precision_search_facade.py
model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py
model_compression_toolkit/common/mixed_precision/search_methods/linear_programming.py
model_compression_toolkit/keras/kpi_data_facade.py
model_compression_toolkit/pytorch/kpi_data_facade.py
tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

Implementation of total KPI metric, which is the sum of total parameters size and max activation tensor.
modified kpi_data API to support the new metric.

Total KPI metric

---

requirements.txt
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Temporary change because of protobuf new version bug:
https://github.com/protocolbuffers/protobuf/issues/10051

Change protobuf to previous version 

---

docsrc/source/api/api_docs/index.rst
docsrc/source/api/experimental_api_docs/index.rst
model_compression_toolkit/common/quantization/core_config.py
model_compression_toolkit/keras/kpi_data_facade.py
model_compression_toolkit/keras/quantization_facade.py
model_compression_toolkit/pytorch/quantization_facade.py

Fix experimental API docs

---

model_compression_toolkit/core/common/collectors/mean_collector.py
model_compression_toolkit/core/common/collectors/min_max_per_channel_collector.py
model_compression_toolkit/core/common/collectors/statistics_collector.py
model_compression_toolkit/core/common/collectors/statistics_collector_generator.py
model_compression_toolkit/core/common/constants.py
model_compression_toolkit/core/common/framework_implementation.py
model_compression_toolkit/core/common/framework_info.py
model_compression_toolkit/core/common/quantization/quantization_analyzer.py
model_compression_toolkit/core/keras/default_framework_info.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/keras/keras_model_validation.py
model_compression_toolkit/core/pytorch/default_framework_info.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py
tests/common_tests/function_tests/test_collectors_manipulation.py

This PR will fix Transformer based pytorch networks.
Fix issue: #250

Set out channel axis per layer

---

model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/permute_call_method.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py
tests/pytorch_tests/model_tests/feature_models/permute_substitution_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Fix argument of permute in case of permute with "call method"

Pytorch Permute substitution

---

model_compression_toolkit/core/common/bias_correction/compute_bias_correction_of_graph.py

Add validation before applying bias correction.

Validation before bias correction

---

model_compression_toolkit/core/analyzer.py
model_compression_toolkit/core/common/bias_correction/apply_bias_correction_to_graph.py
model_compression_toolkit/core/common/mixed_precision/kpi_data.py
model_compression_toolkit/core/common/visualization/nn_visualizer.py
model_compression_toolkit/core/exporter.py
model_compression_toolkit/core/keras/quantization_facade.py
model_compression_toolkit/core/pytorch/quantization_facade.py
model_compression_toolkit/core/runner.py
model_compression_toolkit/gptq/keras/quantization_facade.py
model_compression_toolkit/gptq/pytorch/quantization_facade.py
model_compression_toolkit/gptq/runner.py
model_compression_toolkit/ptq/keras/quantization_facade.py
model_compression_toolkit/ptq/pytorch/quantization_facade.py
model_compression_toolkit/ptq/runner.py
tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py
tests/keras_tests/function_tests/test_uniform_range_selection_weights.py

split and remove post_training_quantization.py into core_runner, ptq_runner, gptq_runner, exporter, analyzer

split post_training_quantization.py blocks

---

docsrc/source/api/api_docs/index.rst
docsrc/source/api/experimental_api_docs/classes/FolderImageLoader.rst
docsrc/source/api/experimental_api_docs/modules/target_platform.rst
docsrc/source/api/experimental_api_docs/notes/tpc_note.rst
docsrc/source/conf.py
model_compression_toolkit/core/keras/kpi_data_facade.py
model_compression_toolkit/core/keras/quantization_facade.py
model_compression_toolkit/core/pytorch/quantization_facade.py
model_compression_toolkit/gptq/keras/quantization_facade.py

Fix sphinx configuration file that caused issue #257.
Add missing type hints.
Fix notes about deprecated API and usage of TPC in MCT.

Fix documentation

---

model_compression_toolkit/core/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py

fix input shape of strided_slice node in MHA decomposition substitution

fix shape in MHA decomposition substitution

---

model_compression_toolkit/core/keras/constants.py
model_compression_toolkit/core/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py

1. remove "shrink_axis_mask" from strided_slice and apply the shrink with reshape node
2. remove "transpose_b" from matmul mode and apply it with Permute node

adjust MHA substitution to supported nodes and attributes

---

model_compression_toolkit/core/common/quantization/quantization_params_generation/power_of_two_selection.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_search.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/symmetric_selection.py

Weight threshold calculation should always be assuming signed quantization

fix weight quantization

---

tests/keras_tests/feature_networks_tests/feature_networks/qat/__init__.py
tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

Test all kernel operations (Conv2D, DW-Conv2D, Dense & Conv2DTranspose) pass QAT

Qat layers test

---

tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py

Increase number of filters in Conv layer in GPTQ test to increase the chance of GPTQ effect on the weights.

Minor fix GPTQ test

---

model_compression_toolkit/qat/keras/quantizer/config_factory.py
model_compression_toolkit/qat/keras/quantizer/configs/weight_quantizer_config.py
model_compression_toolkit/qat/keras/quantizer/ste_rounding/uniform_ste.py
tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/keras_tests/tpc_keras.py

Add UniformQuantizer to QAT and verify SymmetricQuantizer works. Edit QAT tests to activate all quantizers

Add UniformQuantizer to QAT

---

model_compression_toolkit/gptq/pytorch/gptq_graph_info.py
model_compression_toolkit/gptq/pytorch/gptq_training.py
model_compression_toolkit/gptq/pytorch/quantizer/gptq_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/__init__.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/base_gumbel_weights_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/sym_gumbel_weights_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/quant_utils.py
model_compression_toolkit/gptq/pytorch/quantizer/quantizer_wrapper.py
model_compression_toolkit/gptq/pytorch/quantizer/ste_rounding/ste_weights_quantizer.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Phase2: adding Pytorch implementation of GPTQ with Gumbel rounding algorithm

Pytorch GPTQ: Symmetric Gumbel Rounding

---

model_compression_toolkit/core/keras/back2framework/model_gradients.py
model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py
model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/symmetric_gumbel.py
model_compression_toolkit/gptq/keras/quantizer/quant_utils.py

- Changing jacobian weights normalization.
- Replacing temprature parameter quantizer 'clip' with 'ste_clip'.
- Adding a learnable 'scale' to allow better weights parameters learning via GPTQ.

Gumbel Rounding improvements

---

model_compression_toolkit/gptq/common/gptq_constants.py
model_compression_toolkit/gptq/pytorch/gptq_graph_info.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/base_gumbel_weights_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/uniform_gumbel_weights_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/quantizer_wrapper.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Last Phase in GPTQ Pytorch: Implement Uniform Gumbel Rounding

GPTQ Pytorch: Uniform Gumbel rounding

---

model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_quantization_config.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_facade.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py
model_compression_toolkit/core/common/mixed_precision/solution_refinement_procedure.py

Added a mixed-precision refinement procedure, that tries to improve a mixed-precision solution that was found by our mixed-precision optimization algorithm.
Also, non-configurable nodes KPI computation and management was moved into MixedPrecisionSearchManager (to avoid code duplication and allow control on this component in the class that responsible on handling the mixed-precision search).

Mixed-precision refinement procedure

---

model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py
model_compression_toolkit/core/common/similarity_analyzer.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py

Vectorizing the batch loop in the mixed-precision distance matrix computation.
Also, added a few code-level optimizations to the similarity analysis methods to speed up their calculation.

Optimizing distance matrix computation runtime

---

model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py
model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/symmetric_gumbel.py
model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/uniform_gumbel.py
model_compression_toolkit/gptq/keras/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/gptq/keras/quantizer/ste_rounding/uniform_ste.py

1. Change Gumbel rounding perturbation space
2. Update initialization
3. Add STE symmetric and uniform quantizers

Change Gumbel rounding perturbation space

---

.github/workflows/run_tests_suite_all_latest_frameworks.yml
.github/workflows/run_tests_tf210.yml
.github/workflows/run_tests_tf211.yml
.github/workflows/run_tests_torch1_13.yml
README.MD

Update to Pytorch version 1.13

Update to Pytorch version 1.13

---

.github/workflows/run_tests_suite_all_latest_frameworks_python310.yml
.github/workflows/run_tests_suite_all_latest_frameworks_python37.yml
.github/workflows/run_tests_suite_all_latest_frameworks_python38.yml
.github/workflows/run_tests_suite_all_latest_frameworks_python39.yml
model_compression_toolkit/core/common/framework_info.py
model_compression_toolkit/core/common/quantization/quantization_params_fn_selection.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_search.py
tests/test_suite.py

add tests for python 3.9 & 3.10
rename python 3.8 file to explicit name

add tests for python 3.9 & 3.10

---

model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/base_gumbel_weights_quantizer.py
tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Failed when number of epochs is was low. Added tests.

fix gumbel rounding without temperature learning

---

model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_methods.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py
model_compression_toolkit/core/runner.py

Added uncovered cases of non-configurable nodes KPI calculation in mixed precision KPI methods.

Fix non-configurable nodes KPI bug

---

model_compression_toolkit/core/pytorch/back2framework/model_gradients.py
model_compression_toolkit/gptq/common/gptq_constants.py
model_compression_toolkit/gptq/pytorch/gptq_model_builder.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/base_gumbel_weights_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/sym_gumbel_weights_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/gumbel_rounding/uniform_gumbel_weights_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/quant_utils.py
model_compression_toolkit/gptq/pytorch/quantizer/quantizer_wrapper.py
model_compression_toolkit/gptq/pytorch/quantizer/ste_rounding/ste_weights_quantizer.py
tests/pytorch_tests/function_tests/model_gradients_test.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Add update to pytorch GPTQ to align version with tensorflow GPTQ

Update pytorch gptq

---

model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_methods.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py
tests/test_suite.py

- Adding missing log lines that need to be excluded with "no pragma" .
- Adding KPI object tests to test suite

Minor fixes to previous MP coverage PRs

---

tests/pytorch_tests/function_tests/test_function_runner.py
tests/test_suite.py

Also added missing test from Pytorch function tests runner.

Update test suite with missing Keras function tests

---

model_compression_toolkit/core/keras/statistics_correction/__init__.py
model_compression_toolkit/core/pytorch/statistics_correction/__init__.py

The statistics collector package is missing an init file. This PR fixes this.

Add missing init file

---

model_compression_toolkit/core/common/mixed_precision/bit_width_setter.py
model_compression_toolkit/core/common/mixed_precision/distance_weighting.py
model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py
model_compression_toolkit/core/pytorch/mixed_precision/mixed_precision_wrapper.py
tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/keras_tests/function_tests/test_lp_search_bitwidth.py
tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py
tests/test_suite.py

* Removed unused distance function and added dedicated test for the remaining functions.
* Added error message in bit_width_setter.py and in linear_programming.py for missing condition checks.
* Removed unused code from linear_programming.py.
* Excluded several error log lines from the coverage report using "pragma" comment.
* Extended mixed precision tests for several cases (Keras and Pytorch).
* Additional minor changes for increasing coverage.

Mixed precision coverage - final steps

---

model_compression_toolkit/core/common/framework_info.py
model_compression_toolkit/core/common/network_editors/actions.py
model_compression_toolkit/core/common/quantization/quantization_fn_selection.py
model_compression_toolkit/core/common/quantization/quantization_params_fn_selection.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/lut_kmeans_params.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/power_of_two_selection.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_search.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/symmetric_selection.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/uniform_selection.py
model_compression_toolkit/core/common/quantization/quantizers/quantizers_helpers.py
model_compression_toolkit/core/common/quantization/set_node_quantization_config.py
model_compression_toolkit/core/common/statistics_correction/apply_bias_correction_to_graph.py
model_compression_toolkit/core/common/target_platform/op_quantization_config.py
model_compression_toolkit/core/keras/default_framework_info.py
model_compression_toolkit/core/pytorch/default_framework_info.py
model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/tp_model.py
model_compression_toolkit/core/tpc_models/default_tpc/v4_lut/tp_model.py
tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py
tests/keras_tests/feature_networks_tests/feature_networks/test_kmeans_quantizer.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/lut_quantizer_test.py

support symmetric threshold with LUT quantization

Symmetric lut

---

tests/pytorch_tests/model_tests/base_pytorch_test.py

Refactor Pytorch feature tests to run over different TPCs (from a given dict) instead of different quantization configs (which are no longer defining the model's quantization bit-width)

Refactor Pytorch tests to run over TPCs instead of quantization configs

---

tests/keras_tests/function_tests/test_export_keras_fully_quantized_model.py

Different TF versions use different scheme for TFLite tensors indices. This commit fixes the test that assumes a consisting scheme.

Fix export test for TF28 and TF29

---

tests/keras_tests/function_tests/test_fully_quantized_exporter.py

Old exporter used Numpy to quantize the weights of the model, while the new exporter uses TF fake quant method. For this reason the weights are not identical (but almost identical), and the sanity test is updated to quantize the activations only.

Fix exportable model sanity test

---

tests/keras_tests/feature_networks_tests/feature_networks/test_kmeans_quantizer.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

Expand Kmeans quantizer tests  to increase coverage

Kmeans quantizer tests

---

model_compression_toolkit/qat/keras/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/qat/keras/quantizer/ste_rounding/uniform_ste.py
model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/uniform_ste.py
model_compression_toolkit/quantizers_infrastructure/pytorch/quantize_wrapper.py

Register quantization variables in the quantization wrapper

Align QAT keras and PyTorch quantizer initialization

---

model_compression_toolkit/qat/keras/quantizer/quantization_dispatcher_builder.py
model_compression_toolkit/qat/keras/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/qat/keras/quantizer/ste_rounding/uniform_ste.py
model_compression_toolkit/qat/pytorch/quantizer/quantization_dispatcher_builder.py
model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/uniform_ste.py
model_compression_toolkit/quantizers_infrastructure/__init__.py
model_compression_toolkit/quantizers_infrastructure/common/base_trainable_quantizer.py
model_compression_toolkit/quantizers_infrastructure/common/base_trainable_quantizer_config.py
model_compression_toolkit/quantizers_infrastructure/common/constants.py
model_compression_toolkit/quantizers_infrastructure/keras/base_keras_quantizer.py
model_compression_toolkit/quantizers_infrastructure/keras/config_serialization.py
model_compression_toolkit/quantizers_infrastructure/keras/keras_node_quantization_dispatcher.py
model_compression_toolkit/quantizers_infrastructure/pytorch/base_pytorch_quantizer.py
model_compression_toolkit/quantizers_infrastructure/pytorch/quantize_wrapper.py
tests/quantizers_infrastructure_tests/keras_tests/base_keras_infrastructure_test.py
tests/quantizers_infrastructure_tests/keras_tests/test_keras_base_quantizer.py
tests/quantizers_infrastructure_tests/pytorch_tests/base_pytorch_infrastructure_test.py
tests/quantizers_infrastructure_tests/pytorch_tests/test_pytorch_base_quantizer.py

- new class for trainable quantizer config (common for pytorch and tf)
- QAT quantizer, dispatcher and relevant tests update
- small bug fix in quantize_wrapper - wrapper weights should have requires_grad attribute.

Quantizer config 

---

model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_activations_computation.py
tests/keras_tests/feature_networks_tests/feature_networks/symmetric_threshold_selection_activation_test.py
tests/keras_tests/feature_networks_tests/feature_networks/uniform_range_selection_activation_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

Add tests for uniform bounded activation quantization
Add tests for symmetric bounded activation quantization

Add tests for uniform and symmetric activations quantization

---

model_compression_toolkit/core/common/substitutions/batchnorm_reconstruction.py
model_compression_toolkit/core/common/substitutions/batchnorm_refusing.py
tests/keras_tests/feature_networks_tests/feature_networks/second_moment_correction_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

*Check the SMC feature doesn't work with quantization method is POT
*Check the SMC feature work with Uniform quantization
*Check the SMC feature doesn't work without BN in the input model and when the linear layer is being reused

Expand Second Moment correction tests

---

tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

1. Fix DW test
2. Disable loading tests for now (works only in tf2.11)

fix Keras QAT tests 

---

model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
model_compression_toolkit/quantizers_infrastructure/keras/quantize_wrapper.py
tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/function_tests/test_fully_quantized_exporter.py

missing name change from previous PR.
Fix bug in weights saving when using WrapperLayer of keras.

fix exporter naming changes

---

tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py

Increase size of convolutions in tests to increase probability for some of them to change in GPTQ.

Fix GPTQ test

---

model_compression_toolkit/core/keras/back2framework/model_gradients.py
model_compression_toolkit/core/pytorch/back2framework/model_gradients.py
tests/keras_tests/function_tests/test_model_gradients.py
tests/keras_tests/function_tests/test_tensorboard_writer.py
tests/pytorch_tests/function_tests/model_gradients_test.py
tests/pytorch_tests/function_tests/test_function_runner.py

Add tests for model gradient with multiple outputs network. Also fixed a tensorboard test that uses a network with multiple output.

Fix gradients computation with multiple output network

---

model_compression_toolkit/exporter/model_wrapper/keras/builder/node_to_quantizer.py

Fix kwargs creating for uniform quantizers (replacing threshold with min_range when inferring the input rank).

Fix uniform inferable kwargs

---

model_compression_toolkit/gptq/common/gptq_config.py
model_compression_toolkit/gptq/keras/quantizer/soft_rounding/symmetric_soft_quantizer.py
model_compression_toolkit/gptq/pytorch/gptq_training.py
model_compression_toolkit/gptq/pytorch/graph_info.py
model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/__init__.py
model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/symmetric_soft_quantizer.py
tests/pytorch_tests/function_tests/get_gptq_config_test.py
tests/pytorch_tests/function_tests/test_function_runner.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Add SoftQuantizer (Symmetric & PoT) to PyTorch GPTQ

Pytorch soft rounding

---

tutorials/example_pytorch_mobilenet_v2.py

fix: using quantization_config in pytorch_mobilenet_v2 tutorial

---

model_compression_toolkit/gptq/keras/gptq_training.py
model_compression_toolkit/gptq/keras/graph_info.py
model_compression_toolkit/gptq/keras/quantizer/base_keras_gptq_quantizer.py
model_compression_toolkit/gptq/keras/quantizer/soft_rounding/symmetric_soft_quantizer.py
model_compression_toolkit/gptq/keras/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/gptq/pytorch/gptq_training.py
model_compression_toolkit/gptq/pytorch/graph_info.py
model_compression_toolkit/gptq/pytorch/quantizer/base_pytorch_gptq_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/symmetric_soft_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/qat/keras/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/qat/keras/quantizer/ste_rounding/uniform_ste.py
model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/symmetric_ste.py
model_compression_toolkit/qat/pytorch/quantizer/ste_rounding/uniform_ste.py
model_compression_toolkit/quantizers_infrastructure/trainable_infrastructure/common/base_trainable_quantizer.py
model_compression_toolkit/quantizers_infrastructure/trainable_infrastructure/keras/base_keras_quantizer.py
model_compression_toolkit/quantizers_infrastructure/trainable_infrastructure/pytorch/base_pytorch_quantizer.py

Currently, we have 2 groups: 1. Weights 2. Thresholds
All threshold variables are in the Thresholds Group, the rest in the Weights  Group.

trainable variables grouping

---

tests/keras_tests/models_tests/test_networks_runner.py

Networks runner now test new inferable models. Classic TFLite conversion will not work, thus it has been replaced with exporting using the exporter. EfficientNet was marked out since there is an issue with its serialization.

Fix networks runner to use exporter

---

tests/keras_tests/function_tests/test_get_gptq_config.py

(V1 configs were not run after API PR)

Add GPTQ configs to test

---

model_compression_toolkit/gptq/common/gptq_config.py
model_compression_toolkit/gptq/common/gptq_training.py
model_compression_toolkit/gptq/keras/gptq_training.py
model_compression_toolkit/gptq/pytorch/gptq_training.py
tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/keras_tests/function_tests/test_get_gptq_config.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Added class GPTQHessianWeightsConfig with all arguments for computing the Hessian weights, modified Hessian computation methods and extend tests.

Extract GPTQ Hessian computation arguments from GPTQ config

---

model_compression_toolkit/gptq/keras/quantizer/__init__.py
model_compression_toolkit/gptq/keras/quantizer/quant_utils.py
model_compression_toolkit/gptq/keras/quantizer/soft_rounding/uniform_soft_quantizer.py
model_compression_toolkit/gptq/pytorch/quantizer/quant_utils.py
model_compression_toolkit/gptq/pytorch/quantizer/soft_rounding/uniform_soft_quantizer.py
tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

1. Add Keras uniform soft-quantizer
2. Fix Torch uniform soft-quantizer

Add Keras uniform soft-quantizer

---

tests/keras_tests/exporter_tests/test_runner.py
tests/keras_tests/exporter_tests/tflite_fake_quant/__init__.py
tests/keras_tests/exporter_tests/tflite_fake_quant/networks/__init__.py
tests/keras_tests/exporter_tests/tflite_fake_quant/networks/conv2d_test.py
tests/keras_tests/exporter_tests/tflite_fake_quant/tflite_fake_quant_exporter_base_test.py

Add test to check weights in tflite fq weights when quantizing under 8bits

Add test for tflite fq export

---

model_compression_toolkit/core/keras/back2framework/keras_model_builder.py
model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
model_compression_toolkit/gptq/keras/gptq_training.py
model_compression_toolkit/gptq/keras/graph_info.py
model_compression_toolkit/qat/keras/quantization_facade.py
model_compression_toolkit/qat/keras/quantizer/quantization_builder.py
tests/keras_tests/function_tests/test_activation_quantization_holder_gptq.py

Add quantization holder for GPTQ models when activation quantization is needed.

Fix GPTQ issue

---

tests/pytorch_tests/function_tests/test_activation_quantization_holder_gptq.py
tests/pytorch_tests/function_tests/test_fully_quantized_exporter.py
tests/pytorch_tests/model_tests/feature_models/qat_test.py
tests/trainable_infrastructure_tests/pytorch/base_pytorch_trainable_infra_test.py

This PR should be merged simultaneously with another PR for mct_quantizers

fix tests for removal wrapper activation

---

model_compression_toolkit/exporter/model_exporter/keras/fakely_quant_keras_exporter.py
model_compression_toolkit/exporter/model_exporter/keras/keras_export_facade.py
tests/keras_tests/exporter_tests/keras_fake_quant/__init__.py
tests/keras_tests/exporter_tests/keras_fake_quant/keras_fake_quant_exporter_base_test.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/__init__.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/conv2d_test.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/conv2dtranspose_test.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/dense_test.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/dwconv2d_test.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/multiple_inputs_test.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/no_quant_test.py
tests/keras_tests/exporter_tests/keras_fake_quant/networks/tfoplambda_test.py
tests/keras_tests/exporter_tests/test_runner.py
tests/keras_tests/function_tests/test_exporting_qat_models.py

In keras fake-quant export: convert inferable quantizers in holder layers into fake-quant layers

Replace quantizers with fake-quant layers

---

INSTALLATION.md
README.md
tutorials/quick_start/README.md

Add correct links to quick-start guide

Edit README

---

model_compression_toolkit/core/common/substitutions/batchnorm_folding.py
model_compression_toolkit/core/keras/graph_substitutions/substitutions/batchnorm_folding.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/batchnorm_folding.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py
tests/keras_tests/feature_networks_tests/feature_networks/bn_folding_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py
tests/pytorch_tests/model_tests/feature_models/scale_equalization_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Also bug fixes:
* PyTorch BN folding after ConvTranspose2d
* PyTorch scale equalization test

Add BatchNorm forward folding

---

model_compression_toolkit/core/common/quantization/quantization_params_generation/lut_kmeans_params.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/__init__.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/tp_model.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/tpc_keras.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/tpc_pytorch.py
tests/keras_tests/feature_networks_tests/feature_networks/test_kmeans_quantizer.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/keras_tests/function_tests/test_lut_quanitzer_params.py

also: lut_kmeans_params to raise exception if n_bits==multiplier_bits (same behaviour as in activations)

Add TPC: IMX500 v1 LUT

---

.github/workflows/run_tests_suite_pip_keras.yml
INSTALLATION.md
model_compression_toolkit/target_platform_capabilities/tpc_models/get_target_platform_capabilities.py
tutorials/notebooks/example_keras_imagenet.ipynb
tutorials/notebooks/example_keras_qat.ipynb

Just a short cleanup for the remaining unnecessary occurrences of tensorflow-model-optimization

Remove tensorflow-model-optimization from documentation and scripts

---

model_compression_toolkit/target_platform_capabilities/README.md

Fix for issue #726

---

model_compression_toolkit/core/keras/back2framework/model_gradients.py
model_compression_toolkit/core/pytorch/back2framework/model_gradients.py
tests/keras_tests/function_tests/test_model_gradients.py
tests/pytorch_tests/function_tests/model_gradients_test.py
tests/pytorch_tests/function_tests/test_function_runner.py

https://app.clickup.com/t/860r5a0a8

Hessians computation for single interest point

---

.github/workflows/run_keras_tests.yml

Change workflow to run Keras tests parallely

Run Keras tests in parallel

---

model_compression_toolkit/core/common/quantization/quantization_params_generation/lut_kmeans_params.py

Force zero to be one of the kmean clusters

Make sure zero is included in LUT

---

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/__init__.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/tp_model.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/tpc_keras.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/tpc_pytorch.py
tests/keras_tests/function_tests/test_keras_tp_model.py

Add IMX500 TPC with Power-Of-Two weight quantization method

Add IMX500 POT TPC

---

.gitignore
tutorials/notebooks/example_pytorch_ssdlite_mobilenetv3.ipynb
tutorials/quick_start/pytorch_fw/ultralytics_lib/model_lib.py

And some minor fixes to tutorials

Add torch mobnetv3 ssd notebook

---

model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_data.py
model_compression_toolkit/core/graph_prep_runner.py
model_compression_toolkit/core/runner.py
tests/common_tests/helpers/prep_graph_for_func_test.py
tests/keras_tests/feature_networks_tests/feature_networks/network_editor/edit_qc_test.py

Extracting graph preparation from core_runner to an external graph_prep_runner
(This is a step in a larger core runner refactor that will take place in the future)

Extracting graph preparation stage from core_runner

---

.github/workflows/run_tests_suite_pip_keras.yml

Separated the tensorflow and pytorch packages installation when running MCT on each framework

Separated the tensorflow and pytorch packages in pip whl generation test

---

model_compression_toolkit/qat/pytorch/quantizer/lsq/__init__.py
model_compression_toolkit/qat/pytorch/quantizer/lsq/symmetric_lsq.py
model_compression_toolkit/qat/pytorch/quantizer/lsq/uniform_lsq.py
model_compression_toolkit/qat/pytorch/quantizer/quantizer_utils.py
tests/pytorch_tests/model_tests/feature_models/qat_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py
tests/trainable_infrastructure_tests/pytorch/test_pytorch_trainable_infra_runner.py

Add LSQ algorithm for Pytorch  QAT
LSQ: https://arxiv.org/pdf/1902.08153.pdf

LSQ (Pytorch QAT)

---

.github/labeler.yml

Update labeler action labels (to include 'auto') and paths.

Fix labeler paths and labels

---

model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_computation.py

A progress bar indicating the quantization parameters search (weights and activation) has been added, running over the model's node set.
Also added a logger info message indicating that the process has started.

Add progress bar and logger info to quantiation params search

---

tutorials/notebooks/example_keras_qat.ipynb
tutorials/notebooks/example_keras_qat.py
tutorials/notebooks/example_pytorch_qat.py

Add missing SIMD param in QAT tutorials.

Add missing simd param in qat tutorials

---

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1/tpc_pytorch.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_lut/tpc_pytorch.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v1_pot/tpc_pytorch.py

This PR adds torch.argmax to IMX500 TPCs in the NoQuantization section (same as in Keras)

Add torch.argmax to IMX500 TPCs

---

tutorials/quick_start/pytorch_fw/quant.py

Setting use_onnx_custom_quantizer_ops to true in tutorials pytorch ONNX export

---

model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/reshape_with_static_shapes.py
tests/pytorch_tests/model_tests/feature_models/dynamic_size_inputs_test.py

Fix bug in pytorch reshape substitute

---

model_compression_toolkit/core/keras/constants.py
model_compression_toolkit/core/keras/keras_implementation.py
tests/keras_tests/function_tests/test_sensitivity_eval_non_suppoerted_output.py

Exclude combined_non_maximum_supression from Hessian compatible nodes

Exclude combined_non_maximum_supression from Hessian compatible nodes

---

model_compression_toolkit/exporter/README.md
model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py

Update exporter's readme with API last changes.

Adapt exporter readme to API changes

---

requirements.txt

Update the requirements file with the latest version of mctq (1.4).

Update requirements file with mctq 1.4

---

tutorials/notebooks/example_keras_effdet_lite0.ipynb
tutorials/notebooks/example_keras_nanodet_plus.ipynb
tutorials/notebooks/example_keras_yolov8n.ipynb

Update the relevant notebook with a notation to use the latest MCT version.

Update the relevant notebook with a notation to use the latest MCT

---

docsrc/source/api/experimental_api_docs/classes/GradientPTQConfig.rst

Fix GPTQHessianScoresConfig usage in docsrc

---

tutorials/notebooks/example_keras_qat.ipynb

This PR updates the notebook to TF version 2.14.1 and mct-nightly

fix Keras QAT notebook

---

model_compression_toolkit/gptq/keras/quantization_facade.py
model_compression_toolkit/gptq/pytorch/quantization_facade.py
tests/keras_tests/function_tests/test_get_gptq_config.py
tests/pytorch_tests/function_tests/get_gptq_config_test.py

Extend gptq get config API to enable external regularization factor argument

---

tutorials/notebooks/example_keras_imagenet.ipynb

Update the Keras PTQ notebook with a dataset download and make additional minor modifications.

Update the relevant notebook with a stand alone dataset download

---

tutorials/notebooks/example_keras_mobilenet_gptq.ipynb
tutorials/notebooks/example_keras_mobilenet_mixed_precision.ipynb

This PR adds notebooks for Keras Mixed-Precision and GPTQ (adapted from the existing scripts)

Add notebooks for Keras Mixed-Precision and GPTQ

---

tutorials/notebooks/example_keras_mobilenet_gptq.ipynb
tutorials/notebooks/example_keras_mobilenet_mixed_precision.ipynb

fix notebooks colab link

---

model_compression_toolkit/core/runner.py

This PR adds  awarning when running MCT a representative dataset with batch_size==1

Warn batch_size==1 in MCT rep-dataset

---

model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/batchnorm_folding.py
tests/pytorch_tests/model_tests/feature_models/bn_folding_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Fix BN folding for PyTorch ConvTranspose2d with groups>1

Fix BN folding for PyTorch ConvTranspose2d with groups>1

---

tutorials/notebooks/example_keras_yolov8n.ipynb
tutorials/quick_start/pytorch_fw/ultralytics_lib/model_lib.py
tutorials/resources/utils/__init__.py
tutorials/resources/yolov8/yolov8_keras.py
tutorials/resources/yolov8/yolov8_preprocess.py

QuickStart ultralytics - simplify representative dataset loader and solve small problem of batch size

QuickStart ultralytics - simplify representative dataset loader

---

tutorials/notebooks/example_keras_effdet_lite0.ipynb
tutorials/notebooks/example_keras_imagenet.ipynb
tutorials/notebooks/example_keras_mobilenet_gptq.ipynb
tutorials/notebooks/example_keras_mobilenet_mixed_precision.ipynb
tutorials/notebooks/example_keras_nanodet_plus.ipynb
tutorials/notebooks/example_keras_yolov8n.ipynb

Tutorial notebooks - change the paths inside the notebook to relative paths (for testing support)

Change the paths inside the notebook to relative folder paths

---

docs/_sources/api/experimental_api_docs/modules/exporter.rst.txt

Remove un-updated code and information from the export page.

Fix exporter .rst file

---

model_compression_toolkit/__init__.py

Update mct version to v1.11.0

---

tutorials/notebooks/example_keras_network_editor.ipynb

Add a tutorial for Network Editor's basic usage on Keras models.

Add tutorial for Network Editor usage

---

tutorials/notebooks/example_keras_imagenet.ipynb
tutorials/notebooks/example_keras_mobilenet_gptq.ipynb
tutorials/notebooks/example_keras_mobilenet_mixed_precision.ipynb
tutorials/notebooks/example_keras_yolov8n.ipynb

Minor update to several notebooks in order to support notebook tests

Tutorial/notebooks - Minor update to support notebook tests

---

tutorials/notebooks/README.md
tutorials/notebooks/keras/debug_tools/example_keras_network_editor.ipynb
tutorials/notebooks/keras/export/example_keras_export.ipynb
tutorials/notebooks/keras/gptq/example_keras_mobilenet_gptq.ipynb
tutorials/notebooks/keras/pruning/example_keras_pruning_mnist.ipynb
tutorials/notebooks/keras/ptq/example_keras_effdet_lite0.ipynb
tutorials/notebooks/keras/ptq/example_keras_imagenet.ipynb
tutorials/notebooks/keras/ptq/example_keras_mobilenet_mixed_precision.ipynb
tutorials/notebooks/keras/ptq/example_keras_nanodet_plus.ipynb
tutorials/notebooks/keras/ptq/example_keras_yolov8n.ipynb
tutorials/notebooks/keras/qat/example_keras_qat.ipynb
tutorials/notebooks/pytorch/data_generation/example_pytorch_data_generation.ipynb
tutorials/notebooks/pytorch/example_quick_start_torchvision.ipynb
tutorials/notebooks/pytorch/export/example_pytorch_export.ipynb
tutorials/notebooks/pytorch/ptq/example_pytorch_mobilenetv2_cifar100_mixed_precision.ipynb
tutorials/notebooks/pytorch/ptq/example_pytorch_quantization_mnist.ipynb
tutorials/notebooks/pytorch/ptq/example_pytorch_ssdlite_mobilenetv3.ipynb

fix broken links in notebooks readme

---

model_compression_toolkit/core/pytorch/utils.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Fix to scalar representation to support float and integer scalars

support and test scalars in const representation

---

tutorials/quick_start/README.md
tutorials/quick_start/results/model_quantization_results.csv

Update quickstart documentation regarding model name of keras_application

Minor update to quickstart documentation

---

model_compression_toolkit/constants.py
model_compression_toolkit/core/common/quantization/candidate_node_quantization_config.py
model_compression_toolkit/core/common/quantization/set_node_quantization_config.py

Refactoring the class init parameters to explicit parameters names instead of dict with constants.

Refactor CandidateNodeQuantizationConfig init parameters

---

model_compression_toolkit/core/keras/reader/node_builder.py

Replace inspect with tf_inspect so it will support all TF versions

replace inspect with tf_inspect

---

model_compression_toolkit/exporter/README.md
tutorials/notebooks/pytorch/export/example_pytorch_export.ipynb

Remove experimental from exporter readme.
Add inference example in pytorch exporter notebook.

Update exporter readme & add onnx inference example

---

tutorials/notebooks/pytorch/export/example_pytorch_export.ipynb

Use ONNX consistently. Add warning about long inference time in ONNX MCTQ format.

Fixes to export pytorch notebook

---

model_compression_toolkit/gptq/__init__.py
model_compression_toolkit/gptq/common/gptq_config.py
model_compression_toolkit/gptq/keras/quantization_facade.py
model_compression_toolkit/gptq/pytorch/quantization_facade.py
model_compression_toolkit/gptq/runner.py
tests/keras_tests/feature_networks_tests/base_keras_feature_test.py
tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py
tests/keras_tests/function_tests/test_get_gptq_config.py
tests/keras_tests/layer_tests/base_keras_layer_test.py
tests/keras_tests/models_tests/test_networks_runner.py
tests/pytorch_tests/function_tests/get_gptq_config_test.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tutorials/notebooks/keras/gptq/example_keras_mobilenet_gptq.py
tutorials/notebooks/keras/gptq/example_keras_mobilenet_gptq_mixed_precision.py
tutorials/quick_start/keras_fw/quant.py
tutorials/quick_start/pytorch_fw/quant.py

Change GPTQ API methods by removing 'experimental' from their names.

Remove experimental from GPTQ facade API

---

tutorials/quick_start/main.py

Making arguments required in tutorials cli

---

tutorials/notebooks/keras/ptq/example_keras_yolov8n.ipynb

Fix detection notebook that was accordingly missed from PR #972

Fix detection notebook that was missed from PR #972

---

tests/trainable_infrastructure_tests/keras/trainable_keras/test_keras_base_quantizer.py
tutorials/notebooks/keras/ptq/keras_deeplabv3plus_for_imx500.ipynb

Add Keras DeeplabV3+ notebook for quantizing a semantic segmentation model for IMX500

Add keras deeplabv3plus notebook

---

tutorials/quick_start/pytorch_fw/ultralytics_lib/model_lib.py

Quick start - fix a wrong import path in ultralytics mobile_lib

Fix wrong import path in ultralytics mobile_lib

---

model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py
model_compression_toolkit/core/common/similarity_analyzer.py

This PR removes the batch list for MP calculation and use the internal batch flag in the error function. Special care for KL divergence error function.

fix MP batch axis

---

model_compression_toolkit/core/keras/kpi_data_facade.py
model_compression_toolkit/core/pytorch/kpi_data_facade.py
model_compression_toolkit/gptq/keras/quantization_facade.py
model_compression_toolkit/qat/keras/quantization_facade.py
model_compression_toolkit/qat/pytorch/quantization_facade.py
tests/keras_tests/feature_networks_tests/feature_networks/gptq/gptq_test.py
tests/keras_tests/feature_networks_tests/feature_networks/qat/qat_test.py
tests/keras_tests/function_tests/test_exporting_qat_models.py
tests/keras_tests/function_tests/test_get_gptq_config.py
tests/keras_tests/function_tests/test_kpi_data.py
tests/keras_tests/models_tests/test_networks_runner.py
tests/pytorch_tests/exporter_tests/test_exporting_qat_models.py
tests/pytorch_tests/function_tests/kpi_data_test.py
tests/pytorch_tests/model_tests/feature_models/qat_test.py
tutorials/notebooks/keras/gptq/example_keras_mobilenet_gptq_mixed_precision.py
tutorials/notebooks/keras/ptq/example_keras_mobilenet_mixed_precision.py
tutorials/notebooks/keras/ptq/example_keras_mobilenet_mixed_precision_lut.py
tutorials/notebooks/keras/qat/example_keras_qat.py
tutorials/notebooks/pytorch/ptq/example_pytorch_mobilenet_mixed_precision.py
tutorials/notebooks/pytorch/ptq/example_pytorch_mobilenet_mixed_precision_lut.py
tutorials/notebooks/pytorch/ptq/example_pytorch_mobilenetv2_cifar100_mixed_precision.py
tutorials/notebooks/pytorch/qat/example_pytorch_qat.py
tutorials/quick_start/keras_fw/quant.py
tutorials/quick_start/pytorch_fw/quant.py

Remove fw info from API signatures.

Remove fw info from API signatures

---

model_compression_toolkit/core/pytorch/reader/reader.py
tests/pytorch_tests/graph_tests/__init__.py
tests/pytorch_tests/graph_tests/test_fx_errors.py
tests/test_suite.py

Add a specific error for torch.fx failure in pytorch model reader.

Add error for torch.fx failure

---

tutorials/notebooks/keras/export/example_keras_export.ipynb

Add usage example of keras_load_quantized_model.
Replace the resnet50 with mobilenetv2.
Change paths to local paths.
Remove compression ratio calculation in int8.

Edit keras export notebook

---

docsrc/source/api/api_docs/modules/layer_filters.rst
docsrc/source/api/api_docs/modules/target_platform.rst
docsrc/source/api/api_docs/notes/tpc_note.rst
model_compression_toolkit/target_platform_capabilities/target_platform/__init__.py
model_compression_toolkit/target_platform_capabilities/target_platform/fusing.py
model_compression_toolkit/target_platform_capabilities/target_platform/op_quantization_config.py
model_compression_toolkit/target_platform_capabilities/target_platform/targetplatform2framework/operations_to_layers.py

Reorder the TPC page in docsrc so that it now contains only the components of the target_platform modules. In addition, some comments in the target platform components that were not updated have been updated.
See here:
https://reuvenperetz.github.io/model_optimization/api/api_docs/modules/target_platform.html

Rearange TPC page

---

FAQ.md
README.md
model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
model_compression_toolkit/exporter/model_wrapper/pytorch/builder/fully_quantized_model_builder.py
quantization_bag_of_tricks.md
quantization_troubleshooting.md

Add Bag-of-Tricks and FAQ, with links in readme

Add FAQ and bag-of-tricks

---

FAQ.md
README.md
tutorials/README.md
tutorials/notebooks/IMX500_notebooks.md
tutorials/notebooks/MCT_notebooks.md

Fixed broken links in MCT tutorials readme.

MCT tutorials readme - fix broken links

---

model_compression_toolkit/core/pytorch/reader/graph_builders.py

Fix PyTorch reader for FX ImmutableLists
Closes #935

Fix PyTorch reader for FX ImmutableLists

---

tutorials/quick_start/common/utils.py
tutorials/quick_start/pytorch_fw/ultralytics_lib/model_lib.py

Add "FolderImageLoader" to quick start after it was removed from MCT

Add FolderImageLoader to quick start tuorials

---

README.md
model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
model_compression_toolkit/exporter/model_wrapper/pytorch/builder/fully_quantized_model_builder.py
model_compression_toolkit/target_platform_capabilities/README.md
tutorials/notebooks/keras/qat/example_keras_qat.ipynb
tutorials/notebooks/pytorch/ptq/example_pytorch_mobilenetv2_cifar100_mixed_precision.ipynb

Fix FAQ message

---

tutorials/mct_model_garden/models_keras/nanodet/nanodet_keras_model.py

Update nanodet-keras-model in mct_model_garden to support configurable number of classes

Update nanodet tutorial to support configurable number of classes

---

model_compression_toolkit/core/common/quantization/node_quantization_config.py
model_compression_toolkit/core/common/quantization/quantization_config.py
model_compression_toolkit/core/keras/graph_substitutions/substitutions/concat_threshold_update.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/concat_threshold_update.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py
tests/keras_tests/feature_networks_tests/feature_networks/concatination_threshold_update.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/concat_threshold_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

concatenate feature addition. feature updates thresholds previous to a concat layer to match that of concat threshold

concatenate feature addition

---

tutorials/notebooks/pytorch/ptq/pytorch_yolov8n_for_imx500.ipynb

Adding GPTQ to PyTorch Yolov8n OD tutorial

---

requirements.txt
tests/trainable_infrastructure_tests/keras/trainable_keras/test_keras_base_quantizer.py
tests/trainable_infrastructure_tests/pytorch/trainable_pytorch/test_pytorch_base_quantizer.py

Move to MCTQ 1.5.0

---

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/latest/__init__.py
tests/keras_tests/custom_layers_tests/test_sony_ssd_postprocess_layer.py
tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_inputs_test.py
tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_test.py
tests/keras_tests/non_parallel_tests/test_keras_tp_model.py
tests/pytorch_tests/function_tests/test_activation_quantization_holder_gptq.py
tests/pytorch_tests/function_tests/test_pytorch_tp_model.py

Switch default IMX500 TPC to v2

Switch default IMX500 TPC to v2

---

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/latest/__init__.py
tests/keras_tests/non_parallel_tests/test_keras_tp_model.py
tests/pytorch_tests/function_tests/test_activation_quantization_holder_gptq.py
tests/pytorch_tests/function_tests/test_pytorch_tp_model.py

revert default TPC to imx500.v1

---

model_compression_toolkit/core/common/substitutions/remove_identity.py
model_compression_toolkit/core/keras/graph_substitutions/substitutions/remove_identity.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/pytorch/graph_substitutions/substitutions/remove_identity.py
tests/keras_tests/feature_networks_tests/feature_networks/remove_identity_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py

Remove identity layers in keras.
Change Pytorch substitution to use a common function and avoid duplicated code.

Remove identity - Keras

---

model_compression_toolkit/core/common/substitutions/remove_identity.py
tests/keras_tests/feature_networks_tests/feature_networks/remove_identity_test.py
tests/pytorch_tests/model_tests/feature_models/remove_identity_test.py

Fix remove identity substitution when identity is model's output

---

tutorials/notebooks/mct_features_notebooks/keras/example_keras_yolov8n.ipynb

Fix link to colab for yolov8 features tutorial

---

tutorials/notebooks/imx500_notebooks/README.md

Fix broken link in notebook readme

Fix broken link in README

---

model_compression_toolkit/core/pytorch/back2framework/pytorch_model_builder.py
model_compression_toolkit/core/pytorch/utils.py
tests/pytorch_tests/model_tests/feature_models/const_representation_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py
tests/pytorch_tests/pruning_tests/test_pretrained_models.py

Fix automatic conversion of constants to float32 and add support for index constant representation

Fix automatic conversion of constants to float32 and add support for index constant representation

---

tutorials/notebooks/imx500_notebooks/keras/example_keras_mobilenetv2_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/keras/keras_yolov8n_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_mobilevit_xs_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb
tutorials/resources/utils/pytorch_tutorial_tools.py

Update imx500 notebooks for CI testing - a waiver on GPTQ sections and waver on Imagenet download

Update imx500 notebooks for ci testing

---

model_compression_toolkit/target_platform_capabilities/tpc_models/get_target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/qnnpack_tpc/target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/tflite_tpc/target_platform_capabilities.py
tests/keras_tests/feature_networks_tests/feature_networks/tpc_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/tpc_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Refactor TPC factory: only instantiate the requested TPC.

Refactor TPC factory

---

tutorials/notebooks/imx500_notebooks/keras/example_keras_effdet_lite0_for_imx500.ipynb

Add missing import of model_compression_toolkit to effdet notebook

Effdet notebook fix

---

tutorials/mct_model_garden/evaluation_metrics/coco_evaluation.py

The example notebooks crash with the following error:
`SyntaxError: positional argument follows keyword argument`
This pull request fixes the error.

Fix coco_evaluation bug

---

quantization_troubleshooting.md

Added explanation regarding a common error when trying to run mixed precision.

Extend Troubleshooting with resource utilization error scenario

---

tutorials/notebooks/imx500_notebooks/keras/example_keras_nanodet_plus_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/keras/keras_deeplabv3plus_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/keras/keras_yolov8n_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_seg_for_imx500.ipynb

Notebooks update: specify huggingface version in Keras notebooks. Check if dataset exist before download.

Specify huggingface version in Keras notebooks

---

tutorials/mct_model_garden/evaluation_metrics/coco_evaluation.py
tutorials/mct_model_garden/models_pytorch/yolov8/postprocess_yolov8_seg.py
tutorials/mct_model_garden/models_pytorch/yolov8/yolov8-seg.yaml
tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py
tutorials/mct_model_garden/models_pytorch/yolov8/yolov8_postprocess.py
tutorials/mct_model_garden/models_pytorch/yolov8/yolov8n-pose.yaml
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_pose_for_imx500.ipynb

Add YOLOv8n pose estimation tutorial

Yolov8n pose tutorial

---

tutorials/mct_model_garden/models_pytorch/yolov8/yolov8.py
tutorials/notebooks/imx500_notebooks/README.md
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_pose_for_imx500.ipynb

Minor fixes to YOLOv8n pose estimation tutorial and README update

Yolov8n pose tutorial2

---

model_compression_toolkit/core/common/hessian/hessian_info_service.py
model_compression_toolkit/core/common/pruning/importance_metrics/lfh_importance_metric.py
tests/keras_tests/function_tests/test_hessian_info_calculator.py
tests/pytorch_tests/function_tests/test_hessian_info_calculator.py

Fix Hessian scores returned shape and align tests

---

model_compression_toolkit/core/keras/hessian/weights_trace_hessian_calculator_keras.py

Fix weights hessian gradient tape

---

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v3/tpc_pytorch.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v3_lut/tpc_pytorch.py

Adding max pool to Pytorch IMX500 v3 TPC no quantization list

---

tutorials/notebooks/imx500_notebooks/keras/example_keras_effdet_lite0_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/keras/keras_deeplabv3plus_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_pose_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_seg_for_imx500.ipynb

Notebooks minor updates for support testing

Notebooks minor updates for support testing

---

model_compression_toolkit/gptq/pytorch/quantization_facade.py
tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_mobilenet_gptq.ipynb

Add gptq tutorial for torch

---

tutorials/resources/scripts/prepare_imagenet.sh

Tutorials - minot fix in prepare_imagenet.sh script

notebook's prepare_imagenet.sh script minor fix

---

tutorials/notebooks/imx500_notebooks/keras/example_keras_effdet_lite0_for_imx500.ipynb

Fix TF & timm versions in effdet notebook.

Fix TF & timm versions in effdet notebook.

---

tutorials/notebooks/imx500_notebooks/keras/example_keras_mobilenetv2_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_mobilevit_xs_for_imx500.ipynb

- Fix prepare_imagenet script in example_keras_mobilenetv2
-Mobilevit_xs in PyTorch tutorial output in ONNX opset 17

Minor fixes in tutorials

---

tutorials/notebooks/imx500_notebooks/README.md
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_timm_classification_model_for_imx500.ipynb

Results board to imx500 notebooks and 3 additional models to the board + corresponding tutorial.

Results board to the imx500 notebooks readme

---

requirements.txt

Update mctq version in requierments to 1.5.2

Update mctq version in requierments

---

model_compression_toolkit/constants.py
model_compression_toolkit/target_platform_capabilities/tpc_models/get_target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/qnnpack_tpc/target_platform_capabilities.py
model_compression_toolkit/target_platform_capabilities/tpc_models/tflite_tpc/target_platform_capabilities.py

Instead of generating a TPC dictionary for each available fw and each TPC model during import, we create a TPC dictionary for a specific TPC model and requested fw on demand within the function.

Change TPC dictionary by fw into function

---

tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_ptq_mnist.ipynb

Add install to onnx in pytorch_ptq_mnist tutorial

Add onnx install to pytorch ptq tutorial

---

model_compression_toolkit/xquant/common/tensorboard_utils.py
model_compression_toolkit/xquant/keras/tensorboard_utils.py
model_compression_toolkit/xquant/pytorch/tensorboard_utils.py
tutorials/notebooks/mct_features_notebooks/keras/example_keras_activation_threshold_search.ipynb
tutorials/notebooks/mct_features_notebooks/keras/example_keras_activation_z_score_threshold.ipynb
tutorials/notebooks/mct_features_notebooks/keras/example_keras_pruning_mnist.ipynb
tutorials/notebooks/mct_features_notebooks/keras/example_keras_qat.ipynb
tutorials/notebooks/mct_features_notebooks/keras/example_keras_yolov8n.ipynb
tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_pruning_mnist.ipynb

Fix tutorials with missing parts (mainly bad imports).

Fix tutorials

---

tests/keras_tests/function_tests/test_quant_config_filtering.py
tests/pytorch_tests/function_tests/test_quant_config_filtering.py
tests/test_suite.py

Add function test for QC options filtering.

QC options filtering function test

---

tutorials/mct_model_garden/evaluation_metrics/coco_evaluation.py

Tutorials update - modify format_results in coco_evaluation to get unnormalized coordinates bbox

Update format_results to get unnormalized coordinates bbox

---

tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb

YOLOv8n tutorial - added model.eval command before evaluation of the model

Added model.eval which was missing before evalution the model

---

model_compression_toolkit/core/runner.py

Add warning message when using activation mixed precision

Add warning when using activation mixed precision

---

tutorials/mct_model_garden/evaluation_metrics/anomaly_eval.py
tutorials/notebooks/imx500_notebooks/README.md
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_efficient_anomaly_detection.ipynb
tutorials/resources/utils/efficient_ad_utils.py

few mistakes made in previous pull request. the pr makes amendments.
fixing some imports
pulling normalisation in to visulization calculation
fixing output of predict function

efficient ad tutorial fixes

---

tutorials/notebooks/imx500_notebooks/README.md
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_timm_classification_model_for_imx500.ipynb
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_torchvision_classification_model_for_imx500.ipynb

Update the text in generic tutorials for timm and torchvision models

Update the text in tutorials for generic timm and torochvision model

---

.github/dependency-review-config.yml
.github/workflows/dependency_review.yml

Add dependency review workflow to check dependent licenses on PRs.

Add dependency review workflow

---

tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_ptq_mnist.ipynb

Refactor for feature notebook tutorials and modifications to run automatic testing

---

model_compression_toolkit/core/common/graph/base_node.py
model_compression_toolkit/core/common/graph/functional_node.py
model_compression_toolkit/core/keras/back2framework/keras_model_builder.py
model_compression_toolkit/core/keras/reader/node_builder.py
model_compression_toolkit/core/pytorch/back2framework/pytorch_model_builder.py
model_compression_toolkit/core/pytorch/reader/graph_builders.py
model_compression_toolkit/exporter/model_wrapper/keras/builder/fully_quantized_model_builder.py
model_compression_toolkit/exporter/model_wrapper/pytorch/builder/fully_quantized_model_builder.py
tests/keras_tests/feature_networks_tests/feature_networks/const_quantization_test.py
tests/keras_tests/feature_networks_tests/feature_networks/const_representation_test.py
tests/keras_tests/feature_networks_tests/test_features_runner.py
tests/pytorch_tests/model_tests/feature_models/const_quantization_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

Support Keras Merge layers (Add, Concatenate, etc.) in model builder & quantization.
Fix for TF Merge functions (e.g. tf.concat).

Support and fix merge layers (e.g. concat)

---

tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_for_imx500.ipynb

Set the sony-custom-layers installation to release version instead dev version in yolov8 tutorial.

Use formal version of sony-custom-layers

---

model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tp_model.py
model_compression_toolkit/target_platform_capabilities/tpc_models/imx500_tpc/v4/tpc_pytorch.py
tests/pytorch_tests/model_tests/feature_models/const_quantization_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py
tests/pytorch_tests/utils.py

Add torch.Tensor.expand to TPC.v4.
Fix const quantization for torch expand & gather.

Support torch expand with const

---

README.md
tutorials/README.md
tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_xquant.ipynb

Fix small bug in notebook

---

tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolov8n_seg_for_imx500.ipynb

add missing import yolov8seg tutorial

---

.github/workflows/tests_common.yml

From 3.8 to 3.11 (it seems 3.8 is not supported in github workflows anymore).

Update tests_common.yml python version

---

tutorials/mct_model_garden/models_pytorch/yolox/LICENSE
tutorials/mct_model_garden/models_pytorch/yolox/__init__.py
tutorials/mct_model_garden/models_pytorch/yolox/darknet.py
tutorials/mct_model_garden/models_pytorch/yolox/yolox.py
tutorials/mct_model_garden/models_pytorch/yolox/yolox.yaml
tutorials/mct_model_garden/models_pytorch/yolox/yolox_preprocess.py
tutorials/notebooks/imx500_notebooks/pytorch/pytorch_yolox-tiny_for_imx500.ipynb

Add YoloX-Tiny pytorch detection model.

add yolox tutorial for imx500

---

model_compression_toolkit/core/common/hessian/__init__.py
model_compression_toolkit/core/common/hessian/hessian_info_service.py
model_compression_toolkit/core/common/hessian/hessian_scores_request.py
model_compression_toolkit/core/pytorch/hessian/activation_hessian_scores_calculator_pytorch.py
model_compression_toolkit/core/pytorch/hessian/hessian_scores_calculator_pytorch.py
model_compression_toolkit/core/pytorch/hessian/weights_hessian_scores_calculator_pytorch.py
model_compression_toolkit/gptq/common/gptq_config.py
model_compression_toolkit/gptq/common/gptq_training.py
model_compression_toolkit/gptq/pytorch/quantization_facade.py
tests/pytorch_tests/function_tests/test_hessian_info_calculator.py
tests/pytorch_tests/model_tests/feature_models/gptq_test.py
tests/pytorch_tests/model_tests/test_feature_models_runner.py

replace Gaussian with Rademacher distribution in hessian estimation for torch

replace Gaussian with Rademacher distribution in hessian estimation

---

.github/workflows/black_duck_scan.yml

Scan model-compression-kit in Black Duck

---

README.md

Added new paper to the references list and under data generation
- https://arxiv.org/abs/2410.22110

Added Data Generation Arxiv paper reference

---

.github/workflows/run_tests_suite_coverage.yml

Remove the double run of pytest keras in coverage workflow.

Remove the double run of pytest keras

---

model_compression_toolkit/core/common/graph/base_graph.py
model_compression_toolkit/core/common/graph/base_node.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_candidates_filter.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_facade.py
model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py
model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization.py
model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/ru_functions_mapping.py
model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py
model_compression_toolkit/core/common/mixed_precision/sensitivity_evaluation.py
model_compression_toolkit/core/keras/back2framework/mixed_precision_model_builder.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py
tests/keras_tests/non_parallel_tests/test_lp_search_bitwidth.py

Small cosmetic updates in keras mixed precision to improve readability

improve readability

---

.github/workflows/nightly.yml

Update python version in nightly script from 3.8 to 3.12

---

tests/common_tests/helpers/tpcs_for_tests/v4/tp_model.py

Fix tests TPCv4 after TPC refactor

---

.github/workflows/run_tests_suite_coverage.yml

Add context to coverage report.

Add context to coverage report

---

model_compression_toolkit/core/keras/data_util.py
model_compression_toolkit/gptq/keras/gptq_training.py
tests_pytest/keras/core/test_data_util.py

Modify the Keras data_utils datasets to wrap a TensorFlow dataset, ensuring that when a data loader is created, it uses the wrapped TensorFlow dataset directly, rather than recreating it.

Refactor keras data utils

---

model_compression_toolkit/core/common/graph/memory_graph/compute_graph_max_cut.py
model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_calculator.py
model_compression_toolkit/core/common/mixed_precision/resource_utilization_tools/resource_utilization_data.py
model_compression_toolkit/core/runner.py
tests/keras_tests/feature_networks_tests/feature_networks/manual_bit_selection.py

Move maxcut warning so it will only appear once.

Move maxcut warning so it will only appear once.

---

model_compression_toolkit/metadata.py

Add tpc_name to model metadata

---

model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py

Fix mp refinement procedure to run for target RUs only

---

model_compression_toolkit/logger.py
tests/common_tests/function_tests/test_logger.py

Fix Logger info & warning prints. Remove unnecessary prints.

Fix Logger info & warning prints

---

README.md

Images in pypi are not displayed due to usage of relative paths of the images. This PR fixes this issue.

Update README.md with absolute links of images

---

README.md

Changed input required to "Pre trained floating point model (PyTorch/Keras)" instead of "floating point .pt or .keras model"

Changed input required 

---

README.md

Update README.md with WACV2025 paper link

---

model_compression_toolkit/core/common/collectors/histogram_collector.py
model_compression_toolkit/core/common/collectors/statistics_collector.py
model_compression_toolkit/core/common/collectors/weighted_histogram_collector.py
model_compression_toolkit/core/common/framework_implementation.py
model_compression_toolkit/core/common/hessian/hessian_info_service.py
model_compression_toolkit/core/common/hessian/hessian_scores_calculator.py
model_compression_toolkit/core/common/hessian/hessian_scores_request.py
model_compression_toolkit/core/common/model_collector.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/error_functions.py
model_compression_toolkit/core/common/quantization/quantization_params_generation/qparams_activations_computation.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/pytorch/hessian/activation_hessian_scores_calculator_pytorch.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py
model_compression_toolkit/core/quantization_prep_runner.py
tests/keras_tests/function_tests/test_hessian_service.py
tests/keras_tests/function_tests/test_hmse_error_method.py
tests_pytest/common/core/common/collectors/__init__.py
tests_pytest/common/core/common/collectors/test_weighted_histogram_collector.py
tests_pytest/common/core/common/mixed_precision/resource_utilization_tools/test_resource_utilization_calculator.py
tests_pytest/common/core/common/quantization/quantization_params_selection/test_qarams_activations_computation.py
tests_pytest/common/graph_builder_utils.py
tests_pytest/common/test_model_collector.py

Add Hessian-Weighted Histogram for Activation Statistic Collection

---

model_compression_toolkit/core/common/graph/base_node.py
model_compression_toolkit/core/keras/keras_implementation.py
model_compression_toolkit/core/pytorch/pytorch_implementation.py
model_compression_toolkit/target_platform_capabilities/targetplatform2framework/attach2fw.py
model_compression_toolkit/target_platform_capabilities/targetplatform2framework/framework_quantization_capabilities.py
tests_pytest/conftest.py
tests_pytest/keras/core/test_fw_implementation.py
tests_pytest/pytorch/core/test_fw_implementation.py

Fix mac computation for fully connected on non-vector tensor and for stride/dilation conv cases.

Fix mac computation

---

model_compression_toolkit/core/common/collectors/histogram_collector.py

Fix bug in histogram collector

---

tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_activation_z_score_threshold.ipynb

Fix broken link in tutorial

---

model_compression_toolkit/target_platform_capabilities/targetplatform2framework/attach2pytorch.py

Add torch view as a reshape operator in pytorch framework
Will allow 16 bit activation

add torch view as reshape operator

---

.github/workflows/nightly.yml
.github/workflows/run_keras_tests.yml
.github/workflows/run_pytorch_tests.yml
.github/workflows/run_tests_suite_coverage.yml
.github/workflows/tests_common.yml
model_compression_toolkit/exporter/model_wrapper/pytorch/builder/fully_quantized_model_builder.py

1. add a reuse flag to weights quantizers if node is reused
2. change workflow to mctq nightly (temporary)

add reuse flag to weights quantizers

---

tests_pytest/keras_tests/e2e_tests/__init__.py
tests_pytest/pytorch_tests/e2e_tests/__init__.py

Add E2E hierarchy to tests

---

tutorials/notebooks/mct_features_notebooks/pytorch/example_pytorch_export.ipynb

limit onnxruntime-extensions<0.14 in pytorch export feature notebook

---

model_compression_toolkit/target_platform_capabilities/schema/mct_current_schema.py
model_compression_toolkit/target_platform_capabilities/schema/v2.py
model_compression_toolkit/target_platform_capabilities/targetplatform2framework/attach2keras.py
model_compression_toolkit/target_platform_capabilities/targetplatform2framework/attach2pytorch.py
tests_pytest/_fw_tests_common_base/base_tpc_attach2fw_test.py

Back to schema v1, keeping v2 and deleting box decode from schema

Schema - Back to V1

---

model_compression_toolkit/core/common/quantization/filter_nodes_candidates.py
model_compression_toolkit/core/common/quantization/node_quantization_config.py
model_compression_toolkit/target_platform_capabilities/constants.py
tests_pytest/common_tests/unit_tests/core/quantization/node_quantization_config/test_node_weights_quantization_config.py

Will help support TPC IMX500.v5.
In the future need to add manual tool to control the constant quantization config

Add Positional weights quantization config support

---

model_compression_toolkit/core/common/quantization/node_quantization_config.py
tests_pytest/common_tests/unit_tests/core/quantization/node_quantization_config/test_node_weights_quantization_config.py

Fix bug in positional weights quantization config suuport

---

requirements.txt

Update requirements to use mctq nightly.

Update requirements to use mctq nightly

---

README.md

fixed readme banner for Tensorflow versions

---

model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py

Remove node_sort from export

---

.github/workflows/nightly.yml
.github/workflows/run_keras_tests.yml
.github/workflows/run_pytorch_tests.yml
.github/workflows/run_tests_suite_coverage.yml
.github/workflows/tests_common.yml
requirements.txt

Update MCTQ package version in requirements and revert usage of nightly in workflows

---

model_compression_toolkit/core/common/mixed_precision/bit_width_setter.py
model_compression_toolkit/core/common/statistics_correction/compute_activation_bias_correction_of_graph.py
tests/keras_tests/feature_networks_tests/feature_networks/activation_bias_correction_test.py
tests/pytorch_tests/model_tests/feature_models/activation_bias_correction_test.py

Fix activation bias correction with preserving node

---

requirements.txt

Update custom layers version in requirements to >=1.0

---

model_compression_toolkit/core/common/statistics_correction/compute_bias_correction_of_graph.py

Set more informative log in bias correction computation function, and fix typo.

Set more informative log in bias correction computation function.

---

model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py

Fix bug in export using FQ ONNX in replacing activation holder with more than 8 bits with identity

---

model_compression_toolkit/exporter/model_exporter/pytorch/fakely_quant_onnx_pytorch_exporter.py

Replace activation quantizers with identity only when nb>8 and using fakely quant onnx exporter

---

model_compression_toolkit/core/common/mixed_precision/solution_refinement_procedure.py

Refinement checks activation candidates only if activation target is specified, and weights candidates only if weights target is specified. Both are ignored if only total memory is specified. This PR fixes this.

fix greedy refinement - try to refine for total memory

---

model_compression_toolkit/core/common/graph/base_graph.py
model_compression_toolkit/core/common/quantization/candidate_node_quantization_config.py
model_compression_toolkit/core/common/substitutions/shift_negative_activation.py

remove duplicate candidates from node added by SNC

---

README.md
model_compression_toolkit/target_platform_capabilities/targetplatform2framework/attach2pytorch.py
requirements.txt
tests_pytest/pytorch_tests/e2e_tests/test_multiclass_nms_obb.py
tests_pytest/pytorch_tests/unit_tests/target_platform_capabilities/targetplatform2framework/test_attach2pytorch_multiclass_nms_obb.py

* Attach MulticlassNMSOBB in edge-mdt-cl-dev, and add unittests. (#1507)
* Updated repository URLs in README.md. (#1507)
* **Temporary workaround**: Change requirements.txt from edge-mdt-cl to edge-mdt-cl-dev (temporary) (#1506)
* Using the the Nightly release CustomLayer temporary, because the official release CustomLayer supporting MulticlassNMSOBB are not released yet.

[SSS Review] Attach MulticlassNMSOBB

---

.github/dependabot.yml
.github/workflows/publish_release.yml
.github/workflows/run_keras_tests.yml
.github/workflows/run_pytorch_tests.yml

- CICD Maintenance
- Change the reviewer for Dependabot

CICD Maintenance

---

model_compression_toolkit/__init__.py
setup.py

* Update python_requires(from >=3.6 to >=3.9)
* Update Version(from 2.4.2 to 2.4.3)
base branch: patch_v2.4.2(3c1ff38),  the same commit of "Release v2.4.2"(3c1ff38).

[RedSuns, SSS Review] Minor Version Update v.2.4.3 (Update python_requires)

---

model_compression_toolkit/__init__.py
setup.py

* Update python_requires(from >=3.6 to >=3.9)
* Update Version(from 2.4.2 to 2.4.3)
base branch: patch_v2.4.2(3c1ff38),  the same commit of "Release v2.4.2"(3c1ff38).

[RedSuns, SSS Review] Minor Version Update v.2.4.3 (Update python_requires) #1514
